// Generates a complete, self-contained Arduboy2 sketch (.ino) from a
// compiled project. The generated engine mirrors js/emulator.js exactly —
// same bytecode, same update order, same movement constants — so device
// behaviour matches the in-browser play test.
//
// Target: Arduboy / Arduboy FX / Arduboy FX-C (ATmega32u4, board profile
// "Arduboy" or "Arduino Leonardo"). Requires only the Arduboy2 library.

import { compileProject, NO_SCRIPT } from './compiler.js';

function cIdent(name, fallback) {
  const id = String(name || '').replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return id || fallback;
}

function escapeCString(s) {
  let out = '';
  for (const ch of s) {
    const c = ch.charCodeAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === '\\') out += '\\\\';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\f') out += '\\f';
    else if (c >= 32 && c < 127) out += ch;
    else out += '?';
  }
  return out;
}

function byteRows(bytes, perRow = 16, indent = '  ') {
  const parts = [];
  for (let i = 0; i < bytes.length; i += perRow) {
    parts.push(indent + Array.from(bytes.slice(i, i + perRow), (b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  }
  return parts.join('\n');
}

// Public helper for the Image Tool: raw Arduboy-format C array for an image.
export function bitmapToCArray(name, bytes, w, h, withHeader) {
  const all = withHeader ? [w, h, ...bytes] : [...bytes];
  return `// ${w}x${h}${withHeader ? ' (Sprites format: width, height, data)' : ''}\n` +
    `const uint8_t PROGMEM ${cIdent(name, 'image')}[] = {\n${byteRows(Uint8Array.from(all))}\n};\n`;
}

export function generateIno(project) {
  const g = compileProject(project);
  const date = new Date().toISOString().slice(0, 10);

  let out = `/*
 * ${g.name || 'Untitled Game'}${g.author ? ' — by ' + g.author : ''}
 * Generated by ArduStudio on ${date}.
 *
 * Target: Arduboy / Arduboy FX / Arduboy FX-C (ATmega32u4).
 * Libraries needed: Arduboy2 and ArduboyTones (Arduino IDE Library Manager).
 * Board: select "Arduboy" (Arduboy board package) or "Arduino Leonardo".
 *
 * Do not edit below unless you know what you are doing — regenerate from
 * your .ardustudio project instead.
 */

#include <Arduboy2.h>
#include <ArduboyTones.h>
#include <EEPROM.h>

Arduboy2 arduboy;
ArduboyTones sound(arduboy.audio.enabled);

// ---------------------------------------------------------------------------
// Game data
// ---------------------------------------------------------------------------

#define TILE_PX 8
#define NUM_VARS ${Math.max(1, g.varCount)}
#define NO_SCRIPT 0xFFFF

`;

  // ---- tiles (single Sprites-format sheet: w, h, then 8 bytes per tile)
  const tileSheet = [8, 8];
  for (const t of g.tiles) tileSheet.push(...t.bytes);
  out += `// Tileset: ${g.tiles.length} tiles of 8x8 (Sprites frame format)\n`;
  out += `const uint8_t PROGMEM tileset[] = {\n${byteRows(Uint8Array.from(tileSheet))}\n};\n\n`;

  const solidMask = new Uint8Array(Math.ceil(Math.max(1, g.tiles.length) / 8));
  g.tiles.forEach((t, i) => { if (t.solid) solidMask[i >> 3] |= 1 << (i & 7); });
  out += `const uint8_t PROGMEM tileSolidBits[] = {\n${byteRows(solidMask)}\n};\n\n`;

  // ---- sprites
  g.sprites.forEach((s, i) => {
    const arr = [s.width, s.height];
    for (const f of s.frames) arr.push(...f);
    out += `// Sprite ${i}: ${s.name} (${s.width}x${s.height}, ${s.frames.length} frame${s.frames.length === 1 ? '' : 's'})\n`;
    out += `const uint8_t PROGMEM sprite_${i}[] = {\n${byteRows(Uint8Array.from(arr))}\n};\n`;
  });
  out += `\nconst uint8_t* const sprites[] PROGMEM = {\n  ${g.sprites.map((_, i) => `sprite_${i}`).join(', ')}\n};\n`;
  out += `const uint8_t PROGMEM spriteFrameCount[] = { ${g.sprites.map((s) => s.frames.length).join(', ')} };\n\n`;

  // ---- strings
  g.strings.forEach((s, i) => {
    out += `const char str_${i}[] PROGMEM = "${escapeCString(s)}";\n`;
  });
  if (g.strings.length) {
    out += `const char* const strings[] PROGMEM = {\n  ${g.strings.map((_, i) => `str_${i}`).join(', ')}\n};\n\n`;
  } else {
    out += `const char* const strings[] PROGMEM = { nullptr };\n\n`;
  }

  // ---- songs (ArduboyTones sequences)
  g.songs.forEach((s, i) => {
    const words = [];
    for (const n of s.notes) { words.push(n.f, n.d); }
    out += `// Song ${i}: ${s.name} (${s.notes.length} notes)\n`;
    out += `const uint16_t song_${i}[] PROGMEM = {\n  ${words.length ? words.join(', ') + ',' : ''} TONES_END\n};\n`;
  });
  if (g.songs.length) {
    out += `const uint16_t* const songs[] PROGMEM = {\n  ${g.songs.map((_, i) => `song_${i}`).join(', ')}\n};\n`;
    out += `#define NUM_SONGS ${g.songs.length}\n\n`;
  } else {
    out += `const uint16_t* const songs[] PROGMEM = { nullptr };\n#define NUM_SONGS 0\n\n`;
  }

  // ---- script bytecode
  out += `// Script bytecode (${g.code.length} bytes, ${g.scriptOffsets.length} scripts)\n`;
  out += `const uint8_t PROGMEM scriptCode[] = {\n${byteRows(g.code.length ? g.code : new Uint8Array([0]))}\n};\n`;
  out += `const uint16_t PROGMEM scriptOffsets[] = { ${g.scriptOffsets.length ? g.scriptOffsets.join(', ') : 0} };\n\n`;

  // ---- scenes
  out += `struct ActorDef { uint8_t spriteIdx, x, y, movement, flags; uint16_t script; };\n`;
  out += `struct TriggerDef { uint8_t x, y, w, h; uint16_t script; };\n`;
  out += `struct SceneDef {\n  const uint8_t* tiles;\n  const ActorDef* actors;\n  const TriggerDef* triggers;\n  uint8_t w, h;               // scene size in tiles (multi-screen scenes scroll)\n  uint8_t actorCount, triggerCount;\n  uint16_t onEnter;\n};\n\n`;

  g.scenes.forEach((sc, i) => {
    out += `// Scene ${i}: ${sc.name}\n`;
    out += `const uint8_t PROGMEM scene_${i}_tiles[] = {\n${byteRows(Uint8Array.from(sc.tiles))}\n};\n`;
    if (sc.actors.length) {
      out += `const ActorDef scene_${i}_actors[] PROGMEM = {\n`;
      for (const a of sc.actors) {
        const flags = (a.solid ? 1 : 0) | (a.animate ? 2 : 0);
        out += `  { ${a.spriteIdx}, ${a.x}, ${a.y}, ${a.movement}, ${flags}, ${a.scriptIdx === NO_SCRIPT ? 'NO_SCRIPT' : a.scriptIdx} },\n`;
      }
      out += `};\n`;
    }
    if (sc.triggers.length) {
      out += `const TriggerDef scene_${i}_triggers[] PROGMEM = {\n`;
      for (const t of sc.triggers) {
        out += `  { ${t.x}, ${t.y}, ${t.w}, ${t.h}, ${t.scriptIdx === NO_SCRIPT ? 'NO_SCRIPT' : t.scriptIdx} },\n`;
      }
      out += `};\n`;
    }
  });

  out += `\nconst SceneDef scenes[] PROGMEM = {\n`;
  g.scenes.forEach((sc, i) => {
    const actors = sc.actors.length ? `scene_${i}_actors` : 'nullptr';
    const triggers = sc.triggers.length ? `scene_${i}_triggers` : 'nullptr';
    const onEnter = sc.onEnterIdx === NO_SCRIPT ? 'NO_SCRIPT' : sc.onEnterIdx;
    out += `  { scene_${i}_tiles, ${actors}, ${triggers}, ${sc.cols}, ${sc.rows}, ${sc.actors.length}, ${sc.triggers.length}, ${onEnter} },\n`;
  });
  out += `};\n`;

  out += `
#define START_SCENE ${g.startScene}
#define START_X ${g.startX}
#define START_Y ${g.startY}
#define PLAYER_SPRITE ${g.playerSpriteIdx}

// ---------------------------------------------------------------------------
// Engine (mirrors the ArduStudio play-test emulator)
// ---------------------------------------------------------------------------

#define PLAYER_SPEED 2
#define ACTOR_SPEED 1
#define ACTOR_MOVE_INTERVAL 48
#define ANIM_INTERVAL 20
#define TEXT_CHARS_PER_FRAME 2
#define MAX_SCENE_ACTORS 8
#define MAX_TILE_OVERRIDES 16

// Save-game block in EEPROM (matches the emulator's layout):
// [0]=0xA5 [1]=0x5D magic, [2]=scene, [3]=tileX, [4]=tileY, [5..36]=vars
#define SAVE_ADDR EEPROM_STORAGE_SPACE_START
#define SAVE_MAGIC0 0xA5
#define SAVE_MAGIC1 0x5D
#define SAVE_VARS 32

struct ActorState {
  ActorDef def;
  int16_t px, py;
  uint8_t tx, ty;
  uint8_t frame, timer, anim;
  int8_t dir;
  bool moving, hidden, scriptMove;
};

struct TileOverride { uint8_t x, y, t; };

uint8_t vars[NUM_VARS];
ActorState actors[MAX_SCENE_ACTORS];
uint8_t actorCount = 0;
uint8_t sceneIdx = 0;
SceneDef curScene;
uint8_t sceneW = 16, sceneH = 8;
TileOverride overrides[MAX_TILE_OVERRIDES];
uint8_t overrideCount = 0;
int16_t camX = 0, camY = 0;

struct {
  int16_t px, py;
  uint8_t tx, ty;
  int8_t fx, fy;
  uint8_t frame, anim;
  bool moving;
} player;

bool scriptActive = false;
uint16_t scriptPC = 0;
uint8_t scriptSelf = 0xFF;
uint8_t scriptWait = 0;
int8_t scriptWaitActor = -1;
int8_t armedTrigger = -1;
int8_t loopSong = -1; // song index to restart when it finishes, -1 = none

// Dialogue state. textStr points into PROGMEM.
const char* textStr = nullptr;
uint16_t textPageStart = 0;
uint16_t textShown = 0;

uint8_t codeAt(uint16_t pc) { return pgm_read_byte(&scriptCode[pc]); }

uint8_t tileAt(uint8_t x, uint8_t y) {
  for (uint8_t i = 0; i < overrideCount; i++) {
    if (overrides[i].x == x && overrides[i].y == y) return overrides[i].t;
  }
  return pgm_read_byte(curScene.tiles + (uint16_t)y * sceneW + x);
}

void setTile(uint8_t x, uint8_t y, uint8_t t) {
  for (uint8_t i = 0; i < overrideCount; i++) {
    if (overrides[i].x == x && overrides[i].y == y) { overrides[i].t = t; return; }
  }
  if (overrideCount < MAX_TILE_OVERRIDES) {
    overrides[overrideCount].x = x;
    overrides[overrideCount].y = y;
    overrides[overrideCount].t = t;
    overrideCount++;
  }
  // Table full: the change is dropped (same behaviour as the emulator).
}

bool tileSolid(int8_t x, int8_t y) {
  if (x < 0 || x >= (int8_t)sceneW || y < 0 || y >= (int8_t)sceneH) return true;
  uint8_t t = tileAt(x, y);
  return (pgm_read_byte(&tileSolidBits[t >> 3]) >> (t & 7)) & 1;
}

int8_t actorAt(int8_t x, int8_t y, int8_t skip) {
  for (uint8_t i = 0; i < actorCount; i++) {
    if (actors[i].hidden || (int8_t)i == skip) continue;
    int8_t cx = (actors[i].px + TILE_PX / 2) / TILE_PX;
    int8_t cy = (actors[i].py + TILE_PX / 2) / TILE_PX;
    if ((cx == x && cy == y) || (actors[i].tx == x && actors[i].ty == y)) return i;
  }
  return -1;
}

// ---------------------------------------------------------------- save games

bool saveExists() {
  return EEPROM.read(SAVE_ADDR) == SAVE_MAGIC0 &&
         EEPROM.read(SAVE_ADDR + 1) == SAVE_MAGIC1;
}

void saveGame() {
  EEPROM.update(SAVE_ADDR, SAVE_MAGIC0);
  EEPROM.update(SAVE_ADDR + 1, SAVE_MAGIC1);
  EEPROM.update(SAVE_ADDR + 2, sceneIdx);
  EEPROM.update(SAVE_ADDR + 3, (uint8_t)((player.px + TILE_PX / 2) / TILE_PX));
  EEPROM.update(SAVE_ADDR + 4, (uint8_t)((player.py + TILE_PX / 2) / TILE_PX));
  for (uint8_t i = 0; i < SAVE_VARS; i++) {
    EEPROM.update(SAVE_ADDR + 5 + i, i < NUM_VARS ? vars[i] : 0);
  }
}

void deleteSave() {
  EEPROM.update(SAVE_ADDR, 0);
  EEPROM.update(SAVE_ADDR + 1, 0);
}

// ---------------------------------------------------------------------- music

void playSong(uint8_t idx, bool loop) {
  if (idx >= NUM_SONGS) return;
  const uint16_t* s = (const uint16_t*)pgm_read_ptr(&songs[idx]);
  sound.tones(s);
  loopSong = loop ? (int8_t)idx : -1;
}

void stopSong() {
  loopSong = -1;
  sound.noTone();
}

void startScript(uint16_t scriptIdx, uint8_t selfActor) {
  if (scriptIdx == NO_SCRIPT) return;
  scriptActive = true;
  scriptPC = pgm_read_word(&scriptOffsets[scriptIdx]);
  scriptSelf = selfActor;
  scriptWait = 0;
  scriptWaitActor = -1;
  textStr = nullptr;
}

void loadScene(uint8_t idx, uint8_t px, uint8_t py, bool runEnter) {
  sceneIdx = idx;
  memcpy_P(&curScene, &scenes[idx], sizeof(SceneDef));
  sceneW = curScene.w;
  sceneH = curScene.h;
  overrideCount = 0;
  actorCount = curScene.actorCount;
  if (actorCount > MAX_SCENE_ACTORS) actorCount = MAX_SCENE_ACTORS;
  for (uint8_t i = 0; i < actorCount; i++) {
    memcpy_P(&actors[i].def, &curScene.actors[i], sizeof(ActorDef));
    actors[i].px = actors[i].def.x * TILE_PX;
    actors[i].py = actors[i].def.y * TILE_PX;
    actors[i].tx = actors[i].def.x;
    actors[i].ty = actors[i].def.y;
    actors[i].frame = 0;
    actors[i].timer = random(ACTOR_MOVE_INTERVAL);
    actors[i].anim = random(ANIM_INTERVAL);
    actors[i].dir = 1;
    actors[i].moving = false;
    actors[i].hidden = false;
    actors[i].scriptMove = false;
  }
  player.px = px * TILE_PX;
  player.py = py * TILE_PX;
  player.tx = px;
  player.ty = py;
  player.moving = false;
  armedTrigger = -1;
  textStr = nullptr;
  scriptWaitActor = -1;
  if (runEnter && curScene.onEnter != NO_SCRIPT) {
    startScript(curScene.onEnter, 0xFF);
  } else {
    scriptActive = false;
  }
}

bool loadGame() {
  if (!saveExists()) return false;
  for (uint8_t i = 0; i < NUM_VARS && i < SAVE_VARS; i++) {
    vars[i] = EEPROM.read(SAVE_ADDR + 5 + i);
  }
  uint8_t scene = EEPROM.read(SAVE_ADDR + 2);
  if (scene >= ${g.scenes.length}) scene = 0;
  uint8_t px = EEPROM.read(SAVE_ADDR + 3);
  uint8_t py = EEPROM.read(SAVE_ADDR + 4);
  loadScene(scene, px, py, true);
  if (player.tx >= sceneW) { player.tx = 0; player.px = 0; }
  if (player.ty >= sceneH) { player.ty = 0; player.py = 0; }
  return true;
}

uint16_t textPageEnd() {
  uint16_t i = textPageStart;
  while (true) {
    char c = (char)pgm_read_byte(textStr + i);
    if (c == '\\0' || c == '\\f') return i;
    i++;
  }
}

void updateText() {
  uint16_t pageEnd = textPageEnd();
  uint16_t pageLen = pageEnd - textPageStart;
  if (textShown < pageLen) {
    textShown += TEXT_CHARS_PER_FRAME;
    if (textShown > pageLen) textShown = pageLen;
    if (arduboy.justPressed(A_BUTTON) || arduboy.justPressed(B_BUTTON)) textShown = pageLen;
    return;
  }
  if (arduboy.justPressed(A_BUTTON)) {
    if ((char)pgm_read_byte(textStr + pageEnd) == '\\0') {
      textStr = nullptr; // dialogue finished, script resumes next frame
    } else {
      textPageStart = pageEnd + 1;
      textShown = 0;
    }
  }
}

void runScript() {
  if (scriptWait > 0) { scriptWait--; return; }
  if (scriptWaitActor >= 0) {
    if (actors[scriptWaitActor].scriptMove) return; // still walking
    scriptWaitActor = -1;
  }
  if (textStr != nullptr) { updateText(); return; }
  uint16_t guard = 0;
  while (scriptActive && guard++ < 4096) {
    uint8_t op = codeAt(scriptPC++);
    switch (op) {
      case 0: // END
        scriptActive = false;
        break;
      case 1: { // TEXT
        uint8_t idx = codeAt(scriptPC++);
        textStr = (const char*)pgm_read_ptr(&strings[idx]);
        textPageStart = 0;
        textShown = 0;
        return;
      }
      case 2: { // SWITCH_SCENE
        uint8_t sc = codeAt(scriptPC++);
        uint8_t x = codeAt(scriptPC++);
        uint8_t y = codeAt(scriptPC++);
        loadScene(sc, x, y, true);
        if (!scriptActive) return;
        break; // continue into the new scene's onEnter script
      }
      case 3: { // SET_VAR
        uint8_t v = codeAt(scriptPC++);
        uint8_t val = codeAt(scriptPC++);
        if (v < NUM_VARS) vars[v] = val;
        break;
      }
      case 4: { // ADD_VAR
        uint8_t v = codeAt(scriptPC++);
        int8_t d = (int8_t)codeAt(scriptPC++);
        if (v < NUM_VARS) vars[v] += d;
        break;
      }
      case 5: { // IF_VAR
        uint8_t v = codeAt(scriptPC++);
        uint8_t cmp = codeAt(scriptPC++);
        uint8_t val = codeAt(scriptPC++);
        uint16_t elseAddr = codeAt(scriptPC) | ((uint16_t)codeAt(scriptPC + 1) << 8);
        scriptPC += 2;
        uint8_t cur = v < NUM_VARS ? vars[v] : 0;
        bool pass;
        switch (cmp) {
          case 0: pass = cur == val; break;
          case 1: pass = cur != val; break;
          case 2: pass = cur < val; break;
          case 3: pass = cur > val; break;
          case 4: pass = cur <= val; break;
          default: pass = cur >= val; break;
        }
        if (!pass) scriptPC = elseAddr;
        break;
      }
      case 6: { // JUMP
        uint16_t addr = codeAt(scriptPC) | ((uint16_t)codeAt(scriptPC + 1) << 8);
        scriptPC = addr;
        break;
      }
      case 7: { // TONE
        uint16_t f = codeAt(scriptPC) | ((uint16_t)codeAt(scriptPC + 1) << 8);
        scriptPC += 2;
        uint8_t frames = codeAt(scriptPC++);
        stopSong(); // a direct tone interrupts the current song
        sound.tone(f, (uint16_t)(((uint32_t)frames * 50) / 3));
        break;
      }
      case 8: // WAIT
        scriptWait = codeAt(scriptPC++);
        return;
      case 9: case 10: { // ACTOR_HIDE / ACTOR_SHOW
        uint8_t idx = codeAt(scriptPC++);
        if (idx == 0xFF) idx = scriptSelf;
        if (idx < actorCount) actors[idx].hidden = (op == 9);
        break;
      }
      case 11: { // SET_TILE
        uint8_t x = codeAt(scriptPC++);
        uint8_t y = codeAt(scriptPC++);
        uint8_t t = codeAt(scriptPC++);
        setTile(x, y, t);
        break;
      }
      case 12: { // PLAYER_POS
        uint8_t x = codeAt(scriptPC++);
        uint8_t y = codeAt(scriptPC++);
        player.px = x * TILE_PX;
        player.py = y * TILE_PX;
        player.tx = x;
        player.ty = y;
        player.moving = false;
        armedTrigger = -1;
        break;
      }
      case 13: { // ACTOR_MOVE
        uint8_t idx = codeAt(scriptPC++);
        uint8_t x = codeAt(scriptPC++);
        uint8_t y = codeAt(scriptPC++);
        uint8_t flags = codeAt(scriptPC++);
        if (idx == 0xFF) idx = scriptSelf;
        if (idx < actorCount) {
          ActorState& a = actors[idx];
          a.tx = x; a.ty = y;
          if (flags & 1) { // instant
            a.px = x * TILE_PX;
            a.py = y * TILE_PX;
            a.moving = false;
            a.scriptMove = false;
          } else {
            a.scriptMove = true;
            scriptWaitActor = idx;
            return; // block until the actor arrives
          }
        }
        break;
      }
      case 14: { // PLAY_SONG
        uint8_t idx = codeAt(scriptPC++);
        uint8_t flags = codeAt(scriptPC++);
        playSong(idx, flags & 1);
        break;
      }
      case 15: // STOP_SONG
        stopSong();
        break;
      case 16: // SAVE_GAME
        saveGame();
        break;
      case 17: // LOAD_GAME
        if (loadGame()) {
          if (!scriptActive) return;
        }
        break;
      case 18: { // SAVE_CHECK
        uint8_t v = codeAt(scriptPC++);
        if (v < NUM_VARS) vars[v] = saveExists() ? 1 : 0;
        break;
      }
      case 19: // DELETE_SAVE
        deleteSave();
        break;
      default:
        scriptActive = false; // corrupt bytecode — bail out
    }
  }
}

int16_t moveToward(int16_t cur, int16_t goal, int16_t speed) {
  if (cur < goal) return cur + min((int16_t)(goal - cur), speed);
  if (cur > goal) return cur - min((int16_t)(cur - goal), speed);
  return cur;
}

void updatePlayer() {
  if (player.moving) {
    int16_t gx = player.tx * TILE_PX, gy = player.ty * TILE_PX;
    player.px = moveToward(player.px, gx, PLAYER_SPEED);
    player.py = moveToward(player.py, gy, PLAYER_SPEED);
    player.anim++;
    if (player.anim % 8 == 0) player.frame ^= 1;
    if (player.px == gx && player.py == gy) player.moving = false;
    return;
  }
  int8_t dx = 0, dy = 0;
  if (arduboy.pressed(LEFT_BUTTON)) dx = -1;
  else if (arduboy.pressed(RIGHT_BUTTON)) dx = 1;
  else if (arduboy.pressed(UP_BUTTON)) dy = -1;
  else if (arduboy.pressed(DOWN_BUTTON)) dy = 1;

  int8_t cx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t cy = (player.py + TILE_PX / 2) / TILE_PX;

  if (dx || dy) {
    player.fx = dx; player.fy = dy;
    int8_t nx = cx + dx, ny = cy + dy;
    if (nx >= 0 && nx < (int8_t)sceneW && ny >= 0 && ny < (int8_t)sceneH && !tileSolid(nx, ny)) {
      int8_t ai = actorAt(nx, ny, -1);
      if (ai < 0 || !(actors[ai].def.flags & 1)) {
        player.tx = nx; player.ty = ny; player.moving = true;
      }
    }
  }

  if (arduboy.justPressed(A_BUTTON)) {
    int8_t ai = actorAt(cx + player.fx, cy + player.fy, -1);
    if (ai >= 0 && actors[ai].def.script != NO_SCRIPT) {
      startScript(actors[ai].def.script, ai);
    }
  }
}

void checkTriggers() {
  if (player.moving || curScene.triggerCount == 0) return;
  int8_t cx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t cy = (player.py + TILE_PX / 2) / TILE_PX;
  int8_t hit = -1;
  TriggerDef t;
  for (uint8_t i = 0; i < curScene.triggerCount; i++) {
    memcpy_P(&t, &curScene.triggers[i], sizeof(TriggerDef));
    if (cx >= t.x && cx < t.x + t.w && cy >= t.y && cy < t.y + t.h) { hit = i; break; }
  }
  if (hit < 0) { armedTrigger = -1; return; }
  if (hit != armedTrigger) {
    armedTrigger = hit;
    memcpy_P(&t, &curScene.triggers[hit], sizeof(TriggerDef));
    if (t.script != NO_SCRIPT) startScript(t.script, 0xFF);
  }
}

void updateActors(bool allowMove) {
  int8_t pcx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t pcy = (player.py + TILE_PX / 2) / TILE_PX;
  for (uint8_t i = 0; i < actorCount; i++) {
    ActorState& a = actors[i];
    if (a.hidden) continue;
    uint8_t frames = pgm_read_byte(&spriteFrameCount[a.def.spriteIdx]);
    if ((a.def.flags & 2) && frames > 1) {
      a.anim++;
      if (a.anim >= ANIM_INTERVAL) { a.anim = 0; a.frame = (a.frame + 1) % frames; }
    }
    // A scripted Move Actor walks even while the script runs, straight to
    // its target (x first, then y), ignoring collisions.
    if (a.scriptMove) {
      int16_t gx = a.tx * TILE_PX, gy = a.ty * TILE_PX;
      if (a.px != gx) a.px = moveToward(a.px, gx, ACTOR_SPEED);
      else if (a.py != gy) a.py = moveToward(a.py, gy, ACTOR_SPEED);
      if (a.px == gx && a.py == gy) { a.scriptMove = false; a.moving = false; }
      continue;
    }
    if (!allowMove || a.def.movement == 0) continue;
    if (a.moving) {
      int16_t gx = a.tx * TILE_PX, gy = a.ty * TILE_PX;
      a.px = moveToward(a.px, gx, ACTOR_SPEED);
      a.py = moveToward(a.py, gy, ACTOR_SPEED);
      if (a.px == gx && a.py == gy) a.moving = false;
      continue;
    }
    a.timer++;
    if (a.timer < ACTOR_MOVE_INTERVAL) continue;
    a.timer = 0;
    int8_t dx = 0, dy = 0;
    if (a.def.movement == 1) { // wander
      uint8_t d = random(4);
      dx = d == 0 ? -1 : d == 1 ? 1 : 0;
      dy = d == 2 ? -1 : d == 3 ? 1 : 0;
    } else if (a.def.movement == 2) {
      dx = a.dir;
    } else if (a.def.movement == 3) {
      dy = a.dir;
    }
    int8_t nx = a.tx + dx, ny = a.ty + dy;
    bool blocked = nx < 0 || nx >= (int8_t)sceneW || ny < 0 || ny >= (int8_t)sceneH ||
      tileSolid(nx, ny) || actorAt(nx, ny, i) >= 0 ||
      (nx == pcx && ny == pcy) || (nx == player.tx && ny == player.ty);
    if (blocked) {
      if (a.def.movement >= 2) a.dir = -a.dir;
      continue;
    }
    a.tx = nx; a.ty = ny; a.moving = true;
  }
}

void updateCamera() {
  int16_t maxX = (int16_t)sceneW * TILE_PX - 128;
  int16_t maxY = (int16_t)sceneH * TILE_PX - 64;
  camX = player.px - (128 / 2 - TILE_PX / 2);
  camY = player.py - (64 / 2 - TILE_PX / 2);
  if (camX < 0) camX = 0;
  if (camX > maxX) camX = maxX;
  if (camY < 0) camY = 0;
  if (camY > maxY) camY = maxY;
  if (maxX <= 0) camX = 0;
  if (maxY <= 0) camY = 0;
}

void drawTextbox() {
  arduboy.fillRect(0, 38, 128, 26, BLACK);
  arduboy.drawRect(0, 38, 128, 26, WHITE);
  int16_t x = 4, y = 40;
  for (uint16_t i = 0; i < textShown; i++) {
    char c = (char)pgm_read_byte(textStr + textPageStart + i);
    if (c == '\\0' || c == '\\f') break;
    if (c == '\\n') { x = 4; y += 8; continue; }
    arduboy.drawChar(x, y, c, WHITE, BLACK, 1);
    x += 6;
  }
  uint16_t pageLen = textPageEnd() - textPageStart;
  if (textShown >= pageLen && (arduboy.frameCount >> 4) & 1) {
    arduboy.drawPixel(122, 59, WHITE);
    arduboy.drawPixel(123, 59, WHITE);
    arduboy.drawPixel(124, 59, WHITE);
    arduboy.drawPixel(123, 60, WHITE);
  }
}

void drawFrame() {
  arduboy.clear();
  uint8_t tx0 = camX / TILE_PX;
  uint8_t ty0 = camY / TILE_PX;
  uint8_t tx1 = (camX + 127) / TILE_PX;
  uint8_t ty1 = (camY + 63) / TILE_PX;
  if (tx1 >= sceneW) tx1 = sceneW - 1;
  if (ty1 >= sceneH) ty1 = sceneH - 1;
  for (uint8_t ty = ty0; ty <= ty1; ty++) {
    for (uint8_t tx = tx0; tx <= tx1; tx++) {
      Sprites::drawOverwrite(tx * TILE_PX - camX, ty * TILE_PX - camY, tileset, tileAt(tx, ty));
    }
  }
  for (uint8_t i = 0; i < actorCount; i++) {
    ActorState& a = actors[i];
    if (a.hidden) continue;
    const uint8_t* spr = (const uint8_t*)pgm_read_ptr(&sprites[a.def.spriteIdx]);
    Sprites::drawSelfMasked(a.px - camX, a.py - camY, spr, a.frame);
  }
  const uint8_t* pspr = (const uint8_t*)pgm_read_ptr(&sprites[PLAYER_SPRITE]);
  Sprites::drawSelfMasked(player.px - camX, player.py - camY, pspr, player.frame);
  if (scriptActive && textStr != nullptr) drawTextbox();
}

void setup() {
  arduboy.begin();
  arduboy.setFrameRate(60);
  arduboy.initRandomSeed();
  for (uint8_t i = 0; i < NUM_VARS; i++) vars[i] = 0;
  player.fx = 0; player.fy = 1;
  player.frame = 0; player.anim = 0;
  loadScene(START_SCENE, START_X, START_Y, true);
}

void loop() {
  if (!arduboy.nextFrame()) return;
  arduboy.pollButtons();

  // Restart a looping song when it finishes.
  if (loopSong >= 0 && !sound.playing()) {
    const uint16_t* s = (const uint16_t*)pgm_read_ptr(&songs[(uint8_t)loopSong]);
    sound.tones(s);
  }

  if (scriptActive) {
    runScript();
  } else {
    updatePlayer();
    checkTriggers();
  }
  updateActors(!scriptActive);
  updateCamera();

  drawFrame();
  arduboy.display();
}
`;

  return { ino: out, compiled: g, warnings: g.warnings };
}
