// Generates a complete, self-contained Arduboy2 sketch (.ino) from a
// compiled project. The generated engine mirrors js/emulator.js exactly —
// same bytecode, same update order, same movement constants — so device
// behaviour matches the in-browser play test.
//
// Target: Arduboy / Arduboy FX / Arduboy FX-C (ATmega32u4, board profile
// "Arduboy" or "Arduino Leonardo"). Requires only the Arduboy2 library.

import { compileProject, NO_SCRIPT } from './compiler.js';
import {
  MAX_PROJECTILES, SCENE_STACK_DEPTH, FADE_LEVELS,
  PROJECTILE_DIRS, DIRECTIONS,
} from './model.js';
import { EXPR_STACK, EX } from './expression.js';
import { MAX_DRAWN_TEXT } from './compiler.js';

// The generated engine indexes these by direction code, so build the rows in
// code order rather than declaration order.
const PROJ_TABLE = (() => {
  const dx = [], dy = [], facing = [];
  for (const d of PROJECTILE_DIRS) { dx[d.code] = d.dx; dy[d.code] = d.dy; }
  for (const d of DIRECTIONS) {
    const match = PROJECTILE_DIRS.find((p) => p.dx === d.dx && p.dy === d.dy);
    facing[d.code] = match ? match.code : 0;
  }
  return { dx, dy, facing };
})();

// Direction codes by name, so the generated engine cannot drift from the model.
const DIR_CODE = Object.fromEntries(DIRECTIONS.map((d) => [d.key, d.code]));

const SCRIPT_QUEUE_DEPTH = 8;

// Optional engine subsystems are marked in the generated source with
//   //#IF FEATURE … //#ENDIF        (kept only when the game uses it)
//   //#IF !FEATURE … //#ENDIF       (the stand-in when it does not)
// and stripped here. Removing the lines outright rather than wrapping them in
// preprocessor guards keeps the exported .ino readable — a game that never
// shows an overlay has no overlay code in it at all.
function stripFeatures(src, features) {
  const out = [];
  const stack = []; // whether each open region is being kept
  for (const line of src.split('\n')) {
    const open = /^\s*\/\/#IF (!?)([A-Z_]+)\s*$/.exec(line);
    if (open) {
      const want = open[1] !== '!';
      const has = !!features[open[2]];
      stack.push(has === want);
      continue;
    }
    if (/^\s*\/\/#ENDIF\s*$/.test(line)) {
      if (!stack.length) throw new Error('codegen: //#ENDIF without a matching //#IF');
      stack.pop();
      continue;
    }
    if (stack.every(Boolean)) out.push(line);
  }
  if (stack.length) throw new Error('codegen: a //#IF region was never closed');
  return out.join('\n');
}

function cIdent(name, fallback) {
  const id = String(name || '').replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return id || fallback;
}

function escapeCString(s) {
  let out = '';
  for (const ch of s) {
    const c = ch.charCodeAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === '\\') out += '\\\\';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\f') out += '\\f';
    else if (c >= 32 && c < 127) out += ch;
    else if (c > 0 && c < 32) out += '\\' + c.toString(8).padStart(3, '0');
    else out += '?';
  }
  return out;
}

function byteRows(bytes, perRow = 16, indent = '  ') {
  const parts = [];
  for (let i = 0; i < bytes.length; i += perRow) {
    parts.push(indent + Array.from(bytes.slice(i, i + perRow), (b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  }
  return parts.join('\n');
}

// Public helper for the Image Tool: raw Arduboy-format C array for an image.
export function bitmapToCArray(name, bytes, w, h, withHeader) {
  const all = withHeader ? [w, h, ...bytes] : [...bytes];
  return `// ${w}x${h}${withHeader ? ' (Sprites format: width, height, data)' : ''}\n` +
    `const uint8_t PROGMEM ${cIdent(name, 'image')}[] = {\n${byteRows(Uint8Array.from(all))}\n};\n`;
}

export function generateIno(project) {
  const g = compileProject(project);
  const date = new Date().toISOString().slice(0, 10);

  let out = `/*
 * ${g.name || 'Untitled Game'}${g.author ? ' — by ' + g.author : ''}
 * Generated by ArduStudio on ${date}.
 *
 * Target: Arduboy / Arduboy FX / Arduboy FX-C (ATmega32u4).
 * Libraries needed: Arduboy2 and ArduboyTones (Arduino IDE Library Manager).
 * Board: select "Arduboy" (Arduboy board package) or "Arduino Leonardo".
 *
 * Do not edit below unless you know what you are doing — regenerate from
 * your .ardustudio project instead.
 */

#include <Arduboy2.h>
#include <ArduboyTones.h>
#include <EEPROM.h>

Arduboy2 arduboy;
ArduboyTones sound(arduboy.audio.enabled);

// ---------------------------------------------------------------------------
// Game data
// ---------------------------------------------------------------------------

#define TILE_PX 8
#define NUM_VARS ${Math.max(1, g.varCount)}
#define NO_SCRIPT 0xFFFF

`;

  // ---- tiles (single Sprites-format sheet: w, h, then 8 bytes per tile)
  const tileSheet = [8, 8];
  for (const t of g.tiles) tileSheet.push(...t.bytes);
  out += `// Tileset: ${g.tiles.length} tiles of 8x8 (Sprites frame format)\n`;
  out += `const uint8_t PROGMEM tileset[] = {\n${byteRows(Uint8Array.from(tileSheet))}\n};\n\n`;

  const solidMask = new Uint8Array(Math.ceil(Math.max(1, g.tiles.length) / 8));
  g.tiles.forEach((t, i) => { if (t.solid) solidMask[i >> 3] |= 1 << (i & 7); });
  out += `const uint8_t PROGMEM tileSolidBits[] = {\n${byteRows(solidMask)}\n};\n\n`;

  // ---- sprites
  g.sprites.forEach((s, i) => {
    const arr = [s.width, s.height];
    for (const f of s.frames) arr.push(...f);
    out += `// Sprite ${i}: ${s.name} (${s.width}x${s.height}, ${s.frames.length} frame${s.frames.length === 1 ? '' : 's'})\n`;
    out += `const uint8_t PROGMEM sprite_${i}[] = {\n${byteRows(Uint8Array.from(arr))}\n};\n`;
  });
  out += `\nconst uint8_t* const sprites[] PROGMEM = {\n  ${g.sprites.map((_, i) => `sprite_${i}`).join(', ')}\n};\n`;
  out += `const uint8_t PROGMEM spriteFrameCount[] = { ${g.sprites.map((s) => s.frames.length).join(', ')} };\n\n`;

  // ---- strings
  g.strings.forEach((s, i) => {
    out += `const char str_${i}[] PROGMEM = "${escapeCString(s)}";\n`;
  });
  if (g.strings.length) {
    out += `const char* const strings[] PROGMEM = {\n  ${g.strings.map((_, i) => `str_${i}`).join(', ')}\n};\n\n`;
  } else {
    out += `const char* const strings[] PROGMEM = { nullptr };\n\n`;
  }

  // ---- songs (ArduboyTones sequences)
  g.songs.forEach((s, i) => {
    const words = [];
    for (const n of s.notes) { words.push(n.f, n.d); }
    out += `// Song ${i}: ${s.name} (${s.notes.length} notes)\n`;
    out += `const uint16_t song_${i}[] PROGMEM = {\n  ${words.length ? words.join(', ') + ',' : ''} TONES_END\n};\n`;
  });
  if (g.songs.length) {
    out += `const uint16_t* const songs[] PROGMEM = {\n  ${g.songs.map((_, i) => `song_${i}`).join(', ')}\n};\n`;
    out += `#define NUM_SONGS ${g.songs.length}\n\n`;
  } else {
    out += `const uint16_t* const songs[] PROGMEM = { nullptr };\n#define NUM_SONGS 0\n\n`;
  }

  // ---- script bytecode
  out += `// Script bytecode (${g.code.length} bytes, ${g.scriptOffsets.length} scripts)\n`;
  out += `const uint8_t PROGMEM scriptCode[] = {\n${byteRows(g.code.length ? g.code : new Uint8Array([0]))}\n};\n`;
  out += `const uint16_t PROGMEM scriptOffsets[] = { ${g.scriptOffsets.length ? g.scriptOffsets.join(', ') : 0} };\n\n`;

  // ---- scenes
  const scriptRef = (idx) => (idx === NO_SCRIPT ? 'NO_SCRIPT' : idx);

  out += `struct ActorDef {\n  uint8_t spriteIdx, x, y, movement, flags;\n  uint8_t facing, speed, animSpeed, group, collideWith;\n  uint16_t init, interact, hit, update;\n};\n`;
  out += `struct TriggerDef { uint8_t x, y, w, h; uint16_t enter, leave; };\n`;
  out += `struct SceneDef {\n  const uint8_t* tiles;\n  const ActorDef* actors;\n  const TriggerDef* triggers;\n  uint8_t w, h;               // scene size in tiles (multi-screen scenes scroll)\n  uint8_t actorCount, triggerCount;\n  uint16_t init, playerHit;\n};\n\n`;

  g.scenes.forEach((sc, i) => {
    out += `// Scene ${i}: ${sc.name}\n`;
    out += `const uint8_t PROGMEM scene_${i}_tiles[] = {\n${byteRows(Uint8Array.from(sc.tiles))}\n};\n`;
    if (sc.actors.length) {
      out += `const ActorDef scene_${i}_actors[] PROGMEM = {\n`;
      for (const a of sc.actors) {
        const flags = (a.solid ? 1 : 0) | (a.animate ? 2 : 0);
        out += `  { ${a.spriteIdx}, ${a.x}, ${a.y}, ${a.movement}, ${flags},`
          + ` ${a.facing}, ${a.speed}, ${a.animSpeed}, ${a.group}, ${a.collideWith},`
          + ` ${scriptRef(a.scripts.init)}, ${scriptRef(a.scripts.interact)},`
          + ` ${scriptRef(a.scripts.hit)}, ${scriptRef(a.scripts.update)} },\n`;
      }
      out += `};\n`;
    }
    if (sc.triggers.length) {
      out += `const TriggerDef scene_${i}_triggers[] PROGMEM = {\n`;
      for (const t of sc.triggers) {
        out += `  { ${t.x}, ${t.y}, ${t.w}, ${t.h}, ${scriptRef(t.scripts.enter)}, ${scriptRef(t.scripts.leave)} },\n`;
      }
      out += `};\n`;
    }
  });

  out += `\nconst SceneDef scenes[] PROGMEM = {\n`;
  g.scenes.forEach((sc, i) => {
    const actors = sc.actors.length ? `scene_${i}_actors` : 'nullptr';
    const triggers = sc.triggers.length ? `scene_${i}_triggers` : 'nullptr';
    out += `  { scene_${i}_tiles, ${actors}, ${triggers}, ${sc.cols}, ${sc.rows}, ${sc.actors.length}, ${sc.triggers.length}, ${scriptRef(sc.scripts.init)}, ${scriptRef(sc.scripts.playerHit)} },\n`;
  });
  out += `};\n`;

  // Sprite dimensions, needed by collision tests without touching PROGMEM
  // sprite headers on every check.
  out += `const uint8_t PROGMEM spriteW[] = { ${g.sprites.map((s) => s.width).join(', ') || 8} };\n`;
  out += `const uint8_t PROGMEM spriteH[] = { ${g.sprites.map((s) => s.height).join(', ') || 8} };\n`;

  // Animation states: a flat {from,to} table plus per-sprite offsets, which is
  // one PROGMEM array instead of one per sprite.
  const stateRows = [];
  const stateStart = [];
  const stateCount = [];
  for (const spr of g.sprites) {
    stateStart.push(stateRows.length);
    stateCount.push(spr.states.length);
    for (const st of spr.states) stateRows.push(`${st.from}, ${st.to}`);
  }
  out += `const uint8_t PROGMEM spriteStates[] = { ${stateRows.join(', ') || '0, 0'} };\n`;
  out += `const uint8_t PROGMEM spriteStateStart[] = { ${stateStart.join(', ') || 0} };\n`;
  out += `const uint8_t PROGMEM spriteStateCount[] = { ${stateCount.join(', ') || 0} };\n`;

  out += `
#define START_SCENE ${g.startScene}
#define START_X ${g.startX}
#define START_Y ${g.startY}
#define PLAYER_SPRITE ${g.playerSpriteIdx}

// ---------------------------------------------------------------------------
// Engine (mirrors the ArduStudio play-test emulator)
// ---------------------------------------------------------------------------

#define PLAYER_SPEED 2
#define ACTOR_MOVE_INTERVAL 48
#define ANIM_INTERVAL 20
#define TEXT_CHARS_PER_FRAME 2
#define MAX_SCENE_ACTORS 8
#define MAX_TILE_OVERRIDES 16

// Save-game block in EEPROM (matches the emulator's layout):
// [0]=0xA5 [1]=0x5D magic, [2]=scene, [3]=tileX, [4]=tileY, [5..36]=vars
#define SAVE_ADDR EEPROM_STORAGE_SPACE_START
#define SAVE_MAGIC0 0xA5
#define SAVE_MAGIC1 0x5D
#define SAVE_VARS 32

struct ActorState {
  ActorDef def;
  int16_t px, py;
  uint8_t tx, ty;
  uint8_t frame, timer, anim;
  // Per-instance copies of the fields events can change, so def stays the
  // pristine PROGMEM record.
  uint8_t spriteIdx, facing, speed;
  uint8_t effect, effectFrames, subTick;
  uint8_t animSpeed, animFrom, animTo;
  bool animLoop;
  int8_t dir;
  bool moving, hidden, scriptMove;
};

struct TileOverride { uint8_t x, y, t; };

//#IF PROJECTILES
// Projectiles live in a fixed pool — no allocation on an ATmega32u4.
#define MAX_PROJECTILES ${MAX_PROJECTILES}
struct Projectile {
  int16_t px, py;
  int8_t dx, dy;
  uint8_t spriteIdx, life, mask;
  bool active;
};
Projectile projectiles[MAX_PROJECTILES];
//#ENDIF

//#IF SCENE_STACK
// Scenes remembered by Push Scene so Pop Scene can return to them.
#define SCENE_STACK_DEPTH ${SCENE_STACK_DEPTH}
struct SceneStackEntry { uint8_t scene, x, y; };
SceneStackEntry sceneStack[SCENE_STACK_DEPTH];
uint8_t sceneStackTop = 0;
//#ENDIF

// Init and hit scripts waiting for the VM to become free.
#define SCRIPT_QUEUE_DEPTH ${SCRIPT_QUEUE_DEPTH}
struct QueuedScript { uint16_t idx; uint8_t self; };
QueuedScript scriptQueue[SCRIPT_QUEUE_DEPTH];
uint8_t scriptQueueLen = 0;

//#IF FADE
// Ordered-dither fade. Level 0 draws everything, FADE_LEVELS draws nothing.
#define FADE_LEVELS ${FADE_LEVELS}
const uint8_t PROGMEM bayer4[16] = {
  0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5
};
uint8_t fadeLevel = 0, fadeTarget = 0, fadeSpeed = 0, fadeTick = 0;
//#ENDIF

//#IF OVERLAY
// The Game Boy's hardware window, as a software panel: a filled rectangle from
// its corner to the bottom-right of the screen.
struct {
  int16_t px, py, tx, ty;
  uint8_t fill, speed;
  bool on;
} overlay;
uint8_t overlayCutoff = HEIGHT; // overlay and dialogue draw only above this line

// Live Draw Text entries, bounded exactly like the tile override table.
#define MAX_DRAWN_TEXT ${MAX_DRAWN_TEXT}
#define DRAW_TEXT_OVERLAY 1
struct DrawnText { uint8_t strIdx, x, y, location; };
DrawnText drawnText[MAX_DRAWN_TEXT];
uint8_t drawnTextCount = 0;
//#ENDIF

// Expression evaluation stack, sized by the compiler's own limit.
#define EXPR_STACK ${EXPR_STACK}

// dx/dy per projectile direction code, and the direction an actor's facing
// points at. Both mirror the tables in js/emulator.js.
const int8_t PROGMEM projDX[8] = { ${PROJ_TABLE.dx.join(', ')} };
const int8_t PROGMEM projDY[8] = { ${PROJ_TABLE.dy.join(', ')} };
const uint8_t PROGMEM facingToProjDir[4] = { ${PROJ_TABLE.facing.join(', ')} };
#define PROJECTILE_DIR_SOURCE 0xFF
#define PROJECTILE_SRC_SELF 0xFF
#define PROJECTILE_SRC_PLAYER 0xFE
#define COLLIDE_PLAYER 1
#define ACTOR_REF_SELF 0xFF
#define ACTOR_REF_PLAYER 0xFE


uint8_t vars[NUM_VARS];
ActorState actors[MAX_SCENE_ACTORS];
uint8_t actorCount = 0;
uint8_t sceneIdx = 0;
SceneDef curScene;
uint8_t sceneW = 16, sceneH = 8;
TileOverride overrides[MAX_TILE_OVERRIDES];
uint8_t overrideCount = 0;
int16_t camX = 0, camY = 0;

struct {
  int16_t px, py;
  uint8_t tx, ty;
  int8_t fx, fy;
  uint8_t frame, anim;
  bool moving;
} player;

// The player has no facing field, only the direction it last walked.
uint8_t playerFacing() {
  if (player.fy > 0) return ${DIR_CODE.down};
  if (player.fy < 0) return ${DIR_CODE.up};
  if (player.fx < 0) return ${DIR_CODE.left};
  return ${DIR_CODE.right};
}

// A script context. "script" is the blocking VM; "scratch" is reused by every
// On Update script, which must finish inside its frame.
struct ScriptCtx {
  uint16_t pc;
  uint8_t self;
  uint8_t wait;
  uint8_t waitInput;
  int8_t waitActor;
  bool active;
  bool waitFade;
  bool waitOverlay;
};
ScriptCtx script = { 0, 0xFF, 0, 0, -1, false, false, false };
ScriptCtx scratch = { 0, 0xFF, 0, 0, -1, false, false, false };

int8_t armedTrigger = -1;
int8_t armedHit = -1;
int8_t loopSong = -1; // song index to restart when it finishes, -1 = none

// Dialogue state. textStr points into PROGMEM.
const char* textStr = nullptr;
uint16_t textPageStart = 0;
uint16_t textShown = 0;

// Menu state (Display Menu / Display Multiple Choice). Labels point into PROGMEM.
#define MAX_MENU_OPTIONS 8
#define MENU_LAST_IS_ZERO 1
#define MENU_CANCEL_B 2
#define MENU_LAYOUT_DIALOGUE 4
bool menuActive = false;
uint8_t menuVar = 0, menuCount = 0, menuFlags = 0, menuSel = 0;
const char* menuLabels[MAX_MENU_OPTIONS];

// Buttons. The bytecode uses a portable mask (bit0=LEFT .. bit5=B); Arduboy2's
// own constants have a different bit layout that also varies by board variant,
// so always translate through this table rather than hardcoding values.
#define NUM_BUTTONS 6
#define ATTACH_OVERRIDE 1
const uint8_t buttonBits[NUM_BUTTONS] PROGMEM = {
  LEFT_BUTTON, RIGHT_BUTTON, UP_BUTTON, DOWN_BUTTON, A_BUTTON, B_BUTTON
};
// Scripts attached to buttons persist across scene changes until removed.
uint8_t buttonScript[NUM_BUTTONS];
uint8_t buttonOverride = 0;


uint8_t arduboyMask(uint8_t mask) {
  uint8_t out = 0;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (mask & (1 << i)) out |= pgm_read_byte(&buttonBits[i]);
  }
  return out;
}

// Arduboy2::justPressed() takes a single button, so "any of" checks loop.
bool anyJustPressed(uint8_t mask) {
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if ((mask & (1 << i)) && arduboy.justPressed(pgm_read_byte(&buttonBits[i]))) return true;
  }
  return false;
}

// Buttons whose default game action has been replaced by a script.
uint8_t overriddenMask() {
  uint8_t mask = 0;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonScript[i] != 0xFF && (buttonOverride & (1 << i))) {
      mask |= pgm_read_byte(&buttonBits[i]);
    }
  }
  return mask;
}

uint8_t codeAt(uint16_t pc) { return pgm_read_byte(&scriptCode[pc]); }

uint8_t tileAt(uint8_t x, uint8_t y) {
  for (uint8_t i = 0; i < overrideCount; i++) {
    if (overrides[i].x == x && overrides[i].y == y) return overrides[i].t;
  }
  return pgm_read_byte(curScene.tiles + (uint16_t)y * sceneW + x);
}

void setTile(uint8_t x, uint8_t y, uint8_t t) {
  for (uint8_t i = 0; i < overrideCount; i++) {
    if (overrides[i].x == x && overrides[i].y == y) { overrides[i].t = t; return; }
  }
  if (overrideCount < MAX_TILE_OVERRIDES) {
    overrides[overrideCount].x = x;
    overrides[overrideCount].y = y;
    overrides[overrideCount].t = t;
    overrideCount++;
  }
  // Table full: the change is dropped (same behaviour as the emulator).
}

bool tileSolid(int8_t x, int8_t y) {
  if (x < 0 || x >= (int8_t)sceneW || y < 0 || y >= (int8_t)sceneH) return true;
  uint8_t t = tileAt(x, y);
  return (pgm_read_byte(&tileSolidBits[t >> 3]) >> (t & 7)) & 1;
}

int8_t actorAt(int8_t x, int8_t y, int8_t skip) {
  for (uint8_t i = 0; i < actorCount; i++) {
    if (actors[i].hidden || (int8_t)i == skip) continue;
    int8_t cx = (actors[i].px + TILE_PX / 2) / TILE_PX;
    int8_t cy = (actors[i].py + TILE_PX / 2) / TILE_PX;
    if ((cx == x && cy == y) || (actors[i].tx == x && actors[i].ty == y)) return i;
  }
  return -1;
}

// ---------------------------------------------------------------- save games

bool saveExists() {
  return EEPROM.read(SAVE_ADDR) == SAVE_MAGIC0 &&
         EEPROM.read(SAVE_ADDR + 1) == SAVE_MAGIC1;
}

void saveGame() {
  EEPROM.update(SAVE_ADDR, SAVE_MAGIC0);
  EEPROM.update(SAVE_ADDR + 1, SAVE_MAGIC1);
  EEPROM.update(SAVE_ADDR + 2, sceneIdx);
  EEPROM.update(SAVE_ADDR + 3, (uint8_t)((player.px + TILE_PX / 2) / TILE_PX));
  EEPROM.update(SAVE_ADDR + 4, (uint8_t)((player.py + TILE_PX / 2) / TILE_PX));
  for (uint8_t i = 0; i < SAVE_VARS; i++) {
    EEPROM.update(SAVE_ADDR + 5 + i, i < NUM_VARS ? vars[i] : 0);
  }
}

void deleteSave() {
  EEPROM.update(SAVE_ADDR, 0);
  EEPROM.update(SAVE_ADDR + 1, 0);
}

// ---------------------------------------------------------------------- music

void playSong(uint8_t idx, bool loop) {
  if (idx >= NUM_SONGS) return;
  const uint16_t* s = (const uint16_t*)pgm_read_ptr(&songs[idx]);
  sound.tones(s);
  loopSong = loop ? (int8_t)idx : -1;
}

void stopSong() {
  loopSong = -1;
  sound.noTone();
}

// Forward declarations: loadScene starts the first queued init script, and the
// script VM in turn loads scenes.
bool startNextQueued();
void queueScript(uint16_t scriptIdx, uint8_t selfActor);
void startFade(uint8_t target, uint8_t speed);
int16_t moveToward(int16_t cur, int16_t goal, int16_t speed);
uint8_t spriteLastFrame(uint8_t idx);
uint16_t walkText(int16_t x, int16_t y, const char* str, uint16_t from, uint16_t limit, bool draw);

void startScript(uint16_t scriptIdx, uint8_t selfActor) {
  if (scriptIdx == NO_SCRIPT) return;
  script.active = true;
  script.pc = pgm_read_word(&scriptOffsets[scriptIdx]);
  script.self = selfActor;
  script.wait = 0;
  script.waitActor = -1;
  script.waitInput = 0;
  script.waitFade = false;
  script.waitOverlay = false;
  textStr = nullptr;
}

void loadScene(uint8_t idx, uint8_t px, uint8_t py, bool runEnter) {
  sceneIdx = idx;
  memcpy_P(&curScene, &scenes[idx], sizeof(SceneDef));
  sceneW = curScene.w;
  sceneH = curScene.h;
  overrideCount = 0;
  actorCount = curScene.actorCount;
  if (actorCount > MAX_SCENE_ACTORS) actorCount = MAX_SCENE_ACTORS;
  for (uint8_t i = 0; i < actorCount; i++) {
    memcpy_P(&actors[i].def, &curScene.actors[i], sizeof(ActorDef));
    actors[i].px = actors[i].def.x * TILE_PX;
    actors[i].py = actors[i].def.y * TILE_PX;
    actors[i].tx = actors[i].def.x;
    actors[i].ty = actors[i].def.y;
    actors[i].frame = 0;
    actors[i].timer = random(ACTOR_MOVE_INTERVAL);
    actors[i].anim = random(ANIM_INTERVAL);
    actors[i].dir = 1;
    actors[i].moving = false;
    actors[i].hidden = false;
    actors[i].scriptMove = false;
    actors[i].spriteIdx = actors[i].def.spriteIdx;
    actors[i].facing = actors[i].def.facing;
    actors[i].speed = actors[i].def.speed;
    actors[i].effect = 0;
    actors[i].effectFrames = 0;
    actors[i].subTick = 0;
    actors[i].animSpeed = actors[i].def.animSpeed;
    actors[i].animFrom = 0;
    actors[i].animTo = spriteLastFrame(actors[i].spriteIdx);
    actors[i].animLoop = true;
  }
  player.px = px * TILE_PX;
  player.py = py * TILE_PX;
  player.tx = px;
  player.ty = py;
  player.moving = false;
  armedTrigger = -1;
  armedHit = -1;
  textStr = nullptr;
  script.waitActor = -1;
//#IF PROJECTILES
  for (uint8_t i = 0; i < MAX_PROJECTILES; i++) projectiles[i].active = false;
//#ENDIF
//#IF OVERLAY
  drawnTextCount = 0;
  overlay.on = false;
//#ENDIF

  // Actors initialise before the scene does, and any init can block on
  // dialogue, so they queue rather than all running at once.
  scriptQueueLen = 0;
  if (runEnter) {
    for (uint8_t i = 0; i < actorCount; i++) {
      if (actors[i].def.init != NO_SCRIPT && scriptQueueLen < SCRIPT_QUEUE_DEPTH) {
        scriptQueue[scriptQueueLen].idx = actors[i].def.init;
        scriptQueue[scriptQueueLen].self = i;
        scriptQueueLen++;
      }
    }
    if (curScene.init != NO_SCRIPT && scriptQueueLen < SCRIPT_QUEUE_DEPTH) {
      scriptQueue[scriptQueueLen].idx = curScene.init;
      scriptQueue[scriptQueueLen].self = 0xFF;
      scriptQueueLen++;
    }
  }
  if (!startNextQueued()) script.active = false;
}

// Start the next queued script; false when the queue is empty.
bool startNextQueued() {
  if (scriptQueueLen == 0) return false;
  uint16_t idx = scriptQueue[0].idx;
  uint8_t self = scriptQueue[0].self;
  for (uint8_t i = 1; i < scriptQueueLen; i++) scriptQueue[i - 1] = scriptQueue[i];
  scriptQueueLen--;
  startScript(idx, self);
  return true;
}

// Hold a script until the VM is free — a collision can land while dialogue is
// up, and dropping it would lose the hit.
void queueScript(uint16_t scriptIdx, uint8_t selfActor) {
  if (scriptIdx == NO_SCRIPT) return;
  if (!script.active && scriptQueueLen == 0) { startScript(scriptIdx, selfActor); return; }
  if (scriptQueueLen >= SCRIPT_QUEUE_DEPTH) return;
  scriptQueue[scriptQueueLen].idx = scriptIdx;
  scriptQueue[scriptQueueLen].self = selfActor;
  scriptQueueLen++;
}

//#IF FADE
void stepFade() {
  if (fadeLevel == fadeTarget) return;
  if (fadeTick > 0) { fadeTick--; return; }
  fadeTick = fadeSpeed;
  fadeLevel += (fadeLevel < fadeTarget) ? 1 : -1;
}

void startFade(uint8_t target, uint8_t speed) {
  fadeTarget = target > FADE_LEVELS ? FADE_LEVELS : target;
  fadeSpeed = speed;
  fadeTick = speed;
}
//#ENDIF

// Comparison operators, in the order the compiler's CMP table assigns.
bool compareValues(uint8_t cmp, int16_t a, int16_t b) {
  switch (cmp) {
    case 0: return a == b;
    case 1: return a != b;
    case 2: return a < b;
    case 3: return a > b;
    case 4: return a <= b;
    default: return a >= b;
  }
}

// Tile position of an actor reference: 0xFF is the running script's own actor,
// 0xFE the player. Returns false when the reference names nothing.
bool refTile(uint8_t ref, uint8_t self, int16_t& outX, int16_t& outY) {
  if (ref == ACTOR_REF_PLAYER) {
    outX = (player.px + TILE_PX / 2) / TILE_PX;
    outY = (player.py + TILE_PX / 2) / TILE_PX;
    return true;
  }
  uint8_t idx = (ref == ACTOR_REF_SELF) ? self : ref;
  if (idx >= actorCount) return false;
  outX = (actors[idx].px + TILE_PX / 2) / TILE_PX;
  outY = (actors[idx].py + TILE_PX / 2) / TILE_PX;
  return true;
}

// Facing code of an actor reference. The player has no stored facing, only the
// direction it last walked, so derive it from that.
uint8_t refFacing(uint8_t ref, uint8_t self) {
  if (ref == ACTOR_REF_PLAYER) return playerFacing();
  uint8_t idx = (ref == ACTOR_REF_SELF) ? self : ref;
  return idx < actorCount ? actors[idx].facing : 0;
}

//#IF EXPR
// Evaluate compiled expression bytes on a small integer stack. Mirrors
// evalExpression() in js/expression.js exactly, including the int16 wrapping
// and the rule that dividing by zero yields 0 rather than trapping.
int16_t evalExpression(uint16_t at, uint8_t len) {
  int16_t stack[EXPR_STACK];
  uint8_t sp = 0;
  uint16_t end = at + len;
  for (uint16_t i = at; i < end; i++) {
    uint8_t op = codeAt(i);
    if (op == ${EX.PUSH_CONST}) {          // PUSH_CONST
      stack[sp++] = (int16_t)(codeAt(i + 1) | ((uint16_t)codeAt(i + 2) << 8));
      i += 2;
    } else if (op == ${EX.PUSH_VAR}) {     // PUSH_VAR
      uint8_t v = codeAt(++i);
      stack[sp++] = v < NUM_VARS ? vars[v] : 0;
    } else if (op == ${EX.NEG}) {          // NEG
      stack[sp - 1] = -stack[sp - 1];
    } else if (op == ${EX.NOT}) {          // NOT
      stack[sp - 1] = stack[sp - 1] ? 0 : 1;
    } else if (op == ${EX.ABS}) {          // ABS
      if (stack[sp - 1] < 0) stack[sp - 1] = -stack[sp - 1];
    } else if (op == ${EX.RND}) {          // RND
      int16_t n = stack[sp - 1];
      stack[sp - 1] = n > 0 ? (int16_t)random(n) : 0;
    } else {
      int16_t b = stack[--sp];
      int16_t a = stack[sp - 1];
      int16_t r;
      switch (op) {
        case ${EX.ADD}: r = a + b; break;
        case ${EX.SUB}: r = a - b; break;
        case ${EX.MUL}: r = a * b; break;
        case ${EX.DIV}: r = (b == 0) ? 0 : a / b; break;
        case ${EX.MOD}: r = (b == 0) ? 0 : a % b; break;
        case ${EX.EQ}: r = (a == b); break;
        case ${EX.NE}: r = (a != b); break;
        case ${EX.LT}: r = (a < b); break;
        case ${EX.GT}: r = (a > b); break;
        case ${EX.LE}: r = (a <= b); break;
        case ${EX.GE}: r = (a >= b); break;
        case ${EX.AND}: r = (a && b); break;
        case ${EX.OR}: r = (a || b); break;
        case ${EX.MIN}: r = (a < b) ? a : b; break;
        case ${EX.MAX}: r = (a > b) ? a : b; break;
        default: r = 0;
      }
      stack[sp - 1] = r;
    }
  }
  return sp > 0 ? stack[sp - 1] : 0;
}
//#ENDIF

uint8_t spriteLastFrame(uint8_t idx) {
  return pgm_read_byte(&spriteFrameCount[idx]) - 1;
}

//#IF OVERLAY
// Overlay Move To animates towards its target; the script waits for arrival.
void updateOverlay() {
  if (!overlay.on) return;
  if (overlay.speed == 0) { overlay.px = overlay.tx; overlay.py = overlay.ty; return; }
  overlay.px = moveToward(overlay.px, overlay.tx, overlay.speed);
  overlay.py = moveToward(overlay.py, overlay.ty, overlay.speed);
}

bool overlayMoving() {
  return overlay.on && (overlay.px != overlay.tx || overlay.py != overlay.ty);
}

void drawOverlay() {
  if (!overlay.on) return;
  int16_t y = overlay.py;
  int16_t bottom = overlayCutoff < HEIGHT ? overlayCutoff : HEIGHT;
  if (y >= bottom) return;
  arduboy.fillRect(overlay.px, y, WIDTH - overlay.px, bottom - y, overlay.fill ? WHITE : BLACK);
}

//#IF TEXT_VARS
// Walk a PROGMEM string from position 'from', expanding each "$name" marker the
// compiler left behind into that variable's digits. Draws at most 'limit' of the
// characters the player sees (0xFFFF for all of them) and returns how many the
// range holds, so one walk both measures and renders — no RAM buffer, which
// matters more here than the handful of instructions it costs.
uint16_t walkText(int16_t x, int16_t y, const char* str, uint16_t from, uint16_t limit, bool draw) {
  int16_t cx = x, cy = y;
  uint16_t shown = 0;
  for (uint16_t i = from;; i++) {
    char c = (char)pgm_read_byte(str + i);
    if (c == '\\0' || c == '\\f') return shown;
    if (c == '\\n') { cx = x; cy += 8; continue; }
    if (c == 1) {
      // Marker: the next byte is the variable index plus one.
      uint8_t v = (uint8_t)pgm_read_byte(str + (++i)) - 1;
      uint8_t value = v < NUM_VARS ? vars[v] : 0;
      char digits[3];
      uint8_t n = 0;
      do { digits[n++] = '0' + (value % 10); value /= 10; } while (value);
      while (n--) {
        if (shown >= limit) return shown;
        if (draw) arduboy.drawChar(cx, cy, digits[n], WHITE, BLACK, 1);
        cx += 6;
        shown++;
      }
      continue;
    }
    if (shown >= limit) return shown;
    if (draw) arduboy.drawChar(cx, cy, c, WHITE, BLACK, 1);
    cx += 6;
    shown++;
  }
}
//#ENDIF
//#IF !TEXT_VARS
// No text in this game shows a variable, so the walk is a plain copy.
uint16_t walkText(int16_t x, int16_t y, const char* str, uint16_t from, uint16_t limit, bool draw) {
  int16_t cx = x, cy = y;
  uint16_t shown = 0;
  for (uint16_t i = from;; i++) {
    char c = (char)pgm_read_byte(str + i);
    if (c == '\\0' || c == '\\f') return shown;
    if (c == '\\n') { cx = x; cy += 8; continue; }
    if (shown >= limit) return shown;
    if (draw) arduboy.drawChar(cx, cy, c, WHITE, BLACK, 1);
    cx += 6;
    shown++;
  }
}
//#ENDIF

void drawStringAt(int16_t x, int16_t y, const char* str) {
  walkText(x, y, str, 0, 0xFFFF, true);
}

// Background text scrolls with the camera; overlay text is fixed to the screen
// and drawn on top of the panel.
void drawTexts(uint8_t location) {
  for (uint8_t i = 0; i < drawnTextCount; i++) {
    DrawnText& t = drawnText[i];
    if (t.location != location) continue;
    const char* str = (const char*)pgm_read_ptr(&strings[t.strIdx]);
    if (location == DRAW_TEXT_OVERLAY) {
      if (t.y >= overlayCutoff) continue;
      drawStringAt(t.x, t.y, str);
    } else {
      drawStringAt((int16_t)t.x - camX, (int16_t)t.y - camY, str);
    }
  }
}
//#ENDIF

uint8_t spriteWidth(uint8_t idx) { return pgm_read_byte(&spriteW[idx]); }
uint8_t spriteHeight(uint8_t idx) { return pgm_read_byte(&spriteH[idx]); }

bool boxesOverlap(int16_t ax, int16_t ay, uint8_t aw, uint8_t ah,
                  int16_t bx, int16_t by, uint8_t bw, uint8_t bh) {
  return ax < bx + bw && bx < ax + aw && ay < by + bh && by < ay + ah;
}

//#IF COLLISIONS
// The player touching an actor runs that actor's On Hit; an actor in a group
// with nothing to say falls back to the scene's On Player Hit. Like triggers,
// a hit re-arms only once the two separate.
void checkCollisions() {
  uint8_t pw = spriteWidth(PLAYER_SPRITE), ph = spriteHeight(PLAYER_SPRITE);
  for (uint8_t i = 0; i < actorCount; i++) {
    ActorState& a = actors[i];
    if (a.hidden || a.def.group == 0) continue;
    if (!boxesOverlap(a.px, a.py, spriteWidth(a.spriteIdx), spriteHeight(a.spriteIdx),
                      player.px, player.py, pw, ph)) continue;
    if (armedHit == (int8_t)i) return;
    armedHit = i;
    if ((a.def.collideWith & COLLIDE_PLAYER) && a.def.hit != NO_SCRIPT) queueScript(a.def.hit, i);
    else queueScript(curScene.playerHit, i);
    return;
  }
  armedHit = -1;
}
//#ENDIF

//#IF PROJECTILES
void launchProjectile(uint8_t src, uint8_t spriteIdx, uint8_t dirCode,
                      uint8_t speed, uint8_t life, uint8_t mask) {
  int16_t x, y;
  uint8_t facing, srcSprite;
  if (src == PROJECTILE_SRC_PLAYER) {
    x = player.px; y = player.py;
    srcSprite = PLAYER_SPRITE;
    facing = playerFacing();
  } else {
    if (src >= actorCount) return;
    x = actors[src].px; y = actors[src].py;
    facing = actors[src].facing;
    srcSprite = actors[src].spriteIdx;
  }
  uint8_t dir = (dirCode == PROJECTILE_DIR_SOURCE)
    ? pgm_read_byte(&facingToProjDir[facing & 3]) : dirCode;
  for (uint8_t i = 0; i < MAX_PROJECTILES; i++) {
    if (projectiles[i].active) continue;
    Projectile& p = projectiles[i];
    p.active = true;
    p.spriteIdx = spriteIdx;
    // Centred on the launcher, so a big sprite does not shoot from a corner.
    p.px = x + (spriteWidth(srcSprite) - spriteWidth(spriteIdx)) / 2;
    p.py = y + (spriteHeight(srcSprite) - spriteHeight(spriteIdx)) / 2;
    p.dx = (int8_t)pgm_read_byte(&projDX[dir & 7]) * (int8_t)speed;
    p.dy = (int8_t)pgm_read_byte(&projDY[dir & 7]) * (int8_t)speed;
    p.life = life;
    p.mask = mask;
    return;
  }
  // Pool exhausted — the shot is simply dropped.
}
//#ENDIF

//#IF PROJECTILES
void updateProjectiles() {
  for (uint8_t i = 0; i < MAX_PROJECTILES; i++) {
    Projectile& p = projectiles[i];
    if (!p.active) continue;
    p.px += p.dx;
    p.py += p.dy;
    if (--p.life == 0) { p.active = false; continue; }
    uint8_t pw = spriteWidth(p.spriteIdx), ph = spriteHeight(p.spriteIdx);
    int16_t cx = (p.px + pw / 2) / TILE_PX;
    int16_t cy = (p.py + ph / 2) / TILE_PX;
    if (tileSolid(cx, cy)) { p.active = false; continue; }
    for (uint8_t j = 0; j < actorCount; j++) {
      ActorState& a = actors[j];
      if (a.hidden || a.def.group == 0) continue;
      if (!(p.mask & (1 << a.def.group))) continue;
      if (!boxesOverlap(p.px, p.py, pw, ph, a.px, a.py,
                        spriteWidth(a.spriteIdx), spriteHeight(a.spriteIdx))) continue;
      p.active = false;
      if (a.def.hit != NO_SCRIPT) queueScript(a.def.hit, j);
      else queueScript(curScene.playerHit, j);
      break;
    }
  }
}
//#ENDIF

bool loadGame() {
  if (!saveExists()) return false;
  for (uint8_t i = 0; i < NUM_VARS && i < SAVE_VARS; i++) {
    vars[i] = EEPROM.read(SAVE_ADDR + 5 + i);
  }
  uint8_t scene = EEPROM.read(SAVE_ADDR + 2);
  if (scene >= ${g.scenes.length}) scene = 0;
  uint8_t px = EEPROM.read(SAVE_ADDR + 3);
  uint8_t py = EEPROM.read(SAVE_ADDR + 4);
  loadScene(scene, px, py, true);
  if (player.tx >= sceneW) { player.tx = 0; player.px = 0; }
  if (player.ty >= sceneH) { player.ty = 0; player.py = 0; }
  return true;
}

uint16_t textPageEnd() {
  uint16_t i = textPageStart;
  while (true) {
    char c = (char)pgm_read_byte(textStr + i);
    if (c == '\\0' || c == '\\f') return i;
    i++;
  }
}

void updateText() {
  uint16_t pageEnd = textPageEnd();
  uint16_t pageLen = walkText(0, 0, textStr, textPageStart, 0xFFFF, false);
  if (textShown < pageLen) {
    textShown += TEXT_CHARS_PER_FRAME;
    if (textShown > pageLen) textShown = pageLen;
    if (arduboy.justPressed(A_BUTTON) || arduboy.justPressed(B_BUTTON)) textShown = pageLen;
    return;
  }
  if (arduboy.justPressed(A_BUTTON)) {
    if ((char)pgm_read_byte(textStr + pageEnd) == '\\0') {
      textStr = nullptr; // dialogue finished, script resumes next frame
    } else {
      textPageStart = pageEnd + 1;
      textShown = 0;
    }
  }
}

// Rows per column: the dialogue layout is two columns of 4, the menu layout is
// a single column.
uint8_t menuRows() {
  if (menuFlags & MENU_LAYOUT_DIALOGUE) {
    uint8_t r = (menuCount + 1) / 2;
    return r > 4 ? 4 : r;
  }
  return menuCount;
}

// Value an option yields: 1-based, unless it is the last option and the script
// asked for the last option to mean 0.
uint8_t menuValue(uint8_t i) {
  if ((menuFlags & MENU_LAST_IS_ZERO) && i == menuCount - 1) return 0;
  return i + 1;
}

void closeMenu(uint8_t value) {
  if (menuVar < NUM_VARS) vars[menuVar] = value;
  menuActive = false;
}

void updateMenu() {
  uint8_t rows = menuRows();
  if (arduboy.justPressed(UP_BUTTON)) menuSel = (menuSel + menuCount - 1) % menuCount;
  else if (arduboy.justPressed(DOWN_BUTTON)) menuSel = (menuSel + 1) % menuCount;
  else if (menuFlags & MENU_LAYOUT_DIALOGUE) {
    // Left/right hop between the two columns.
    if (arduboy.justPressed(LEFT_BUTTON)) menuSel = (menuSel + menuCount - rows) % menuCount;
    else if (arduboy.justPressed(RIGHT_BUTTON)) menuSel = (menuSel + rows) % menuCount;
  }
  if (arduboy.justPressed(A_BUTTON)) {
    closeMenu(menuValue(menuSel));
    return;
  }
  if ((menuFlags & MENU_CANCEL_B) && arduboy.justPressed(B_BUTTON)) {
    closeMenu(0);
  }
}

void drawMenuLabel(int16_t x, int16_t y, const char* label) {
  walkText(x, y, label, 0, 20, true);
}

void drawMenu() {
  uint8_t rows = menuRows();
  if (menuFlags & MENU_LAYOUT_DIALOGUE) {
    // Full-width box at the bottom, two columns of up to 4 rows.
    arduboy.fillRect(0, 30, 128, 34, BLACK);
    arduboy.drawRect(0, 30, 128, 34, WHITE);
    for (uint8_t i = 0; i < menuCount; i++) {
      int16_t x = 4 + (i / rows) * 62;
      int16_t y = 32 + (i % rows) * 8;
      if (i == menuSel) arduboy.drawChar(x, y, '>', WHITE, BLACK, 1);
      drawMenuLabel(x + 6, y, menuLabels[i]);
    }
  } else {
    // Single column down the right-hand side.
    uint8_t h = menuCount * 8 + 2;
    if (h > 64) h = 64;
    arduboy.fillRect(64, 0, 64, h, BLACK);
    arduboy.drawRect(64, 0, 64, h, WHITE);
    for (uint8_t i = 0; i < menuCount; i++) {
      int16_t y = 1 + i * 8;
      if (i == menuSel) arduboy.drawChar(67, y, '>', WHITE, BLACK, 1);
      drawMenuLabel(73, y, menuLabels[i]);
    }
  }
}

void runScript(ScriptCtx& s) {
  if (s.wait > 0) { s.wait--; return; }
//#IF FADE
  if (s.waitFade) {
    if (fadeLevel != fadeTarget) return;
    s.waitFade = false;
  }
//#ENDIF
//#IF OVERLAY
  if (s.waitOverlay) {
    if (overlayMoving()) return;
    s.waitOverlay = false;
  }
//#ENDIF
  if (s.waitActor >= 0) {
    if (actors[s.waitActor].scriptMove) return; // still walking
    s.waitActor = -1;
  }
  if (s.waitInput) {
    if (!anyJustPressed(s.waitInput)) return; // blocked until pressed
    s.waitInput = 0;
  }
  if (menuActive) { updateMenu(); return; }
  if (textStr != nullptr) { updateText(); return; }
  uint16_t guard = 0;
  while (s.active && guard++ < 4096) {
    uint8_t op = codeAt(s.pc++);
    switch (op) {
      case 0: // END
        s.active = false;
        break;
      case 1: { // TEXT
        uint8_t idx = codeAt(s.pc++);
        textStr = (const char*)pgm_read_ptr(&strings[idx]);
        textPageStart = 0;
        textShown = 0;
        return;
      }
      case 2: { // SWITCH_SCENE
        uint8_t sc = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        loadScene(sc, x, y, true);
        if (&s != &script) { s.active = false; return; } // update script: its actor is gone
        if (!s.active) return;
        break; // continue into the new scene's init scripts
      }
      case 3: { // SET_VAR
        uint8_t v = codeAt(s.pc++);
        uint8_t val = codeAt(s.pc++);
        if (v < NUM_VARS) vars[v] = val;
        break;
      }
      case 4: { // ADD_VAR
        uint8_t v = codeAt(s.pc++);
        int8_t d = (int8_t)codeAt(s.pc++);
        if (v < NUM_VARS) vars[v] += d;
        break;
      }
      case 5: { // IF_VAR
        uint8_t v = codeAt(s.pc++);
        uint8_t cmp = codeAt(s.pc++);
        uint8_t val = codeAt(s.pc++);
        uint16_t elseAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        uint8_t cur = v < NUM_VARS ? vars[v] : 0;
        bool pass;
        switch (cmp) {
          case 0: pass = cur == val; break;
          case 1: pass = cur != val; break;
          case 2: pass = cur < val; break;
          case 3: pass = cur > val; break;
          case 4: pass = cur <= val; break;
          default: pass = cur >= val; break;
        }
        if (!pass) s.pc = elseAddr;
        break;
      }
      case 6: { // JUMP
        uint16_t addr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc = addr;
        break;
      }
      case 7: { // TONE
        uint16_t f = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        uint8_t frames = codeAt(s.pc++);
        stopSong(); // a direct tone interrupts the current song
        sound.tone(f, (uint16_t)(((uint32_t)frames * 50) / 3));
        break;
      }
      case 8: // WAIT
        s.wait = codeAt(s.pc++);
        return;
      case 9: case 10: { // ACTOR_HIDE / ACTOR_SHOW
        uint8_t idx = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) actors[idx].hidden = (op == 9);
        break;
      }
      case 11: { // SET_TILE
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint8_t t = codeAt(s.pc++);
        setTile(x, y, t);
        break;
      }
      case 12: { // PLAYER_POS
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        player.px = x * TILE_PX;
        player.py = y * TILE_PX;
        player.tx = x;
        player.ty = y;
        player.moving = false;
        armedTrigger = -1;
        break;
      }
      case 13: { // ACTOR_MOVE
        uint8_t idx = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint8_t flags = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) {
          ActorState& a = actors[idx];
          a.tx = x; a.ty = y;
          if (flags & 1) { // instant
            a.px = x * TILE_PX;
            a.py = y * TILE_PX;
            a.moving = false;
            a.scriptMove = false;
          } else {
            a.scriptMove = true;
            s.waitActor = idx;
            return; // block until the actor arrives
          }
        }
        break;
      }
      case 14: { // PLAY_SONG
        uint8_t idx = codeAt(s.pc++);
        uint8_t flags = codeAt(s.pc++);
        playSong(idx, flags & 1);
        break;
      }
      case 15: // STOP_SONG
        stopSong();
        break;
      case 16: // SAVE_GAME
        saveGame();
        break;
      case 17: // LOAD_GAME
        if (loadGame()) {
          if (&s != &script) { s.active = false; return; }
          if (!s.active) return;
        }
        break;
      case 18: { // SAVE_CHECK
        uint8_t v = codeAt(s.pc++);
        if (v < NUM_VARS) vars[v] = saveExists() ? 1 : 0;
        break;
      }
      case 19: // DELETE_SAVE
        deleteSave();
        break;
      case 20: { // SET_LED
        uint8_t mode = codeAt(s.pc++);
        uint8_t r = codeAt(s.pc++);
        uint8_t g = codeAt(s.pc++);
        uint8_t b = codeAt(s.pc++);
        if (mode == 1) {
          // Digital: hand the pins back from PWM first, then switch channels.
          arduboy.freeRGBled();
          arduboy.digitalWriteRGB(RED_LED, r ? RGB_ON : RGB_OFF);
          arduboy.digitalWriteRGB(GREEN_LED, g ? RGB_ON : RGB_OFF);
          arduboy.digitalWriteRGB(BLUE_LED, b ? RGB_ON : RGB_OFF);
        } else {
          arduboy.setRGBled(r, g, b);
        }
        break;
      }
      case 22: { // SET_ACTOR_SPRITE
        uint8_t idx = codeAt(s.pc++);
        uint8_t spriteIdx = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) {
          actors[idx].spriteIdx = spriteIdx;
          // The new sprite may have fewer frames than the old one.
          if (actors[idx].frame >= pgm_read_byte(&spriteFrameCount[spriteIdx])) {
            actors[idx].frame = 0;
          }
        }
        break;
      }
      case 23: { // ATTACH_SCRIPT
        uint8_t btn = codeAt(s.pc++);
        uint8_t flags = codeAt(s.pc++);
        uint8_t idx = codeAt(s.pc++);
        if (btn < NUM_BUTTONS) {
          buttonScript[btn] = idx;
          if (flags & ATTACH_OVERRIDE) buttonOverride |= (1 << btn);
          else buttonOverride &= ~(1 << btn);
        }
        break;
      }
      case 24: { // REMOVE_BUTTON_SCRIPT
        uint8_t btn = codeAt(s.pc++);
        if (btn < NUM_BUTTONS) {
          buttonScript[btn] = 0xFF;
          buttonOverride &= ~(1 << btn);
        }
        break;
      }
      case 25: // WAIT_INPUT
        s.waitInput = codeAt(s.pc++);
        return; // block until one of them is pressed
      case 26: { // IF_INPUT
        uint8_t mask = codeAt(s.pc++);
        uint16_t elseAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        // Held right now — this checks once and never waits.
        if (!arduboy.pressed(arduboyMask(mask))) s.pc = elseAddr;
        break;
      }
      case 27: { // SET_ACTOR_DIR
        uint8_t idx = codeAt(s.pc++);
        uint8_t dir = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) actors[idx].facing = dir;
        break;
      }
      case 28: { // SET_ACTOR_SPEED
        uint8_t idx = codeAt(s.pc++);
        uint8_t speed = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) { actors[idx].speed = speed; actors[idx].subTick = 0; }
        break;
      }
      case 29: { // ACTOR_EFFECT
        uint8_t idx = codeAt(s.pc++);
        uint8_t effect = codeAt(s.pc++);
        uint8_t frames = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) { actors[idx].effect = effect; actors[idx].effectFrames = frames; }
        break;
      }
      //#IF PROJECTILES
      case 30: { // LAUNCH_PROJECTILE
        uint8_t src = codeAt(s.pc++);
        uint8_t spriteIdx = codeAt(s.pc++);
        uint8_t dir = codeAt(s.pc++);
        uint8_t speed = codeAt(s.pc++);
        uint8_t life = codeAt(s.pc++);
        uint8_t mask = codeAt(s.pc++);
        if (src == PROJECTILE_SRC_SELF) src = s.self;
        if (src == PROJECTILE_SRC_PLAYER || src < actorCount) {
          launchProjectile(src, spriteIdx, dir, speed, life, mask);
        }
        break;
      }
//#ENDIF
      //#IF SCENE_STACK
      case 31: { // PUSH_SCENE
        uint8_t sc = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint8_t speed = codeAt(s.pc++);
        if (sceneStackTop < SCENE_STACK_DEPTH) {
          sceneStack[sceneStackTop].scene = sceneIdx;
          sceneStack[sceneStackTop].x = (player.px + TILE_PX / 2) / TILE_PX;
          sceneStack[sceneStackTop].y = (player.py + TILE_PX / 2) / TILE_PX;
          sceneStackTop++;
        }
        loadScene(sc, x, y, true);
        fadeLevel = FADE_LEVELS;
        startFade(0, speed);
        if (&s != &script) { s.active = false; return; }
        if (!s.active) return;
        break;
      }
      case 32: // POP_SCENE
      case 33: { // POP_ALL_SCENES
        uint8_t speed = codeAt(s.pc++);
        if (sceneStackTop == 0) break; // nothing pushed — carry on
        uint8_t at = (op == 33) ? 0 : sceneStackTop - 1;
        SceneStackEntry back = sceneStack[at];
        sceneStackTop = (op == 33) ? 0 : sceneStackTop - 1;
        loadScene(back.scene, back.x, back.y, true);
        fadeLevel = FADE_LEVELS;
        startFade(0, speed);
        if (&s != &script) { s.active = false; return; }
        if (!s.active) return;
        break;
      }
//#ENDIF
//#IF FADE
      case 34: // FADE_IN
      case 35: { // FADE_OUT
        uint8_t speed = codeAt(s.pc++);
        startFade(op == 35 ? FADE_LEVELS : 0, speed);
        s.waitFade = true;
        return; // block until the fade finishes
      }
//#ENDIF
      case 36: { // IF_ACTOR_AT
        uint8_t ref = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint16_t elseAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        int16_t ax, ay;
        if (!refTile(ref, s.self, ax, ay) || ax != x || ay != y) s.pc = elseAddr;
        break;
      }
      case 37: { // IF_ACTOR_DISTANCE
        uint8_t ref = codeAt(s.pc++);
        uint8_t cmp = codeAt(s.pc++);
        uint16_t distSq = codeAt(s.pc++);
        distSq |= (uint16_t)codeAt(s.pc++) << 8;
        uint8_t fromRef = codeAt(s.pc++);
        uint16_t elseAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        int16_t ax, ay, bx, by;
        bool pass = false;
        if (refTile(ref, s.self, ax, ay) && refTile(fromRef, s.self, bx, by)) {
          int16_t dx = ax - bx, dy = ay - by;
          pass = compareValues(cmp, dx * dx + dy * dy, (int16_t)distSq);
        }
        if (!pass) s.pc = elseAddr;
        break;
      }
      case 38: { // STORE_ACTOR_DIR
        uint8_t ref = codeAt(s.pc++);
        uint8_t v = codeAt(s.pc++);
        if (v < NUM_VARS) vars[v] = refFacing(ref, s.self);
        break;
      }
      case 39: { // STORE_ACTOR_POS
        uint8_t ref = codeAt(s.pc++);
        uint8_t vx = codeAt(s.pc++);
        uint8_t vy = codeAt(s.pc++);
        int16_t ax, ay;
        if (refTile(ref, s.self, ax, ay)) {
          if (vx < NUM_VARS) vars[vx] = ax;
          if (vy < NUM_VARS) vars[vy] = ay;
        }
        break;
      }
      //#IF EXPR
      case 40: { // EXPR_IF
        uint8_t len = codeAt(s.pc++);
        int16_t value = evalExpression(s.pc, len);
        s.pc += len;
        uint16_t elseAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        if (!value) s.pc = elseAddr;
        break;
      }
      case 41: { // EXPR_LOOP
        uint8_t len = codeAt(s.pc++);
        int16_t value = evalExpression(s.pc, len);
        s.pc += len;
        uint16_t endAddr = codeAt(s.pc) | ((uint16_t)codeAt(s.pc + 1) << 8);
        s.pc += 2;
        if (!value) s.pc = endAddr;
        break;
      }
//#ENDIF
      case 42: // SEED_RNG
        arduboy.initRandomSeed();
        break;
      //#IF SWITCH
      case 43: { // SWITCH
        uint8_t v = codeAt(s.pc++);
        uint8_t cur = v < NUM_VARS ? vars[v] : 0;
        uint8_t count = codeAt(s.pc++);
        uint16_t target = 0;
        bool found = false;
        for (uint8_t i = 0; i < count; i++) {
          uint16_t at = s.pc + (uint16_t)i * 3;
          if (!found && codeAt(at) == cur) {
            target = codeAt(at + 1) | ((uint16_t)codeAt(at + 2) << 8);
            found = true;
          }
        }
        uint16_t elseAt = s.pc + (uint16_t)count * 3;
        s.pc = found ? target : (codeAt(elseAt) | ((uint16_t)codeAt(elseAt + 1) << 8));
        break;
      }
//#ENDIF
      case 44: { // SET_ANIM_FRAME
        uint8_t idx = codeAt(s.pc++);
        uint8_t frame = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) {
          uint8_t last = spriteLastFrame(actors[idx].spriteIdx);
          actors[idx].frame = frame < last ? frame : last;
        }
        break;
      }
      case 45: { // SET_ANIM_SPEED
        uint8_t idx = codeAt(s.pc++);
        uint8_t speed = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) { actors[idx].animSpeed = speed; actors[idx].anim = 0; }
        break;
      }
      case 46: { // SET_ANIM_STATE
        uint8_t idx = codeAt(s.pc++);
        uint8_t stateIdx = codeAt(s.pc++);
        uint8_t loop = codeAt(s.pc++);
        if (idx == 0xFF) idx = s.self;
        if (idx < actorCount) {
          ActorState& a = actors[idx];
          if (stateIdx < pgm_read_byte(&spriteStateCount[a.spriteIdx])) {
            uint8_t at = pgm_read_byte(&spriteStateStart[a.spriteIdx]) + stateIdx;
            a.animFrom = pgm_read_byte(&spriteStates[at * 2]);
            a.animTo = pgm_read_byte(&spriteStates[at * 2 + 1]);
            a.animLoop = loop != 0;
            a.frame = a.animFrom;
            a.anim = 0;
          }
        }
        break;
      }
      //#IF OVERLAY
      case 47: { // SHOW_OVERLAY
        uint8_t fill = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        overlay.on = true;
        overlay.fill = fill;
        overlay.px = overlay.tx = (int16_t)x * TILE_PX;
        overlay.py = overlay.ty = (int16_t)y * TILE_PX;
        overlay.speed = 0;
        break;
      }
      case 48: // HIDE_OVERLAY
        overlay.on = false;
        break;
      case 49: { // OVERLAY_MOVE
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint8_t speed = codeAt(s.pc++);
        overlay.tx = (int16_t)x * TILE_PX;
        overlay.ty = (int16_t)y * TILE_PX;
        overlay.speed = speed;
        if (!overlay.on || speed == 0) {
          overlay.px = overlay.tx;
          overlay.py = overlay.ty;
          break;
        }
        s.waitOverlay = true;
        return; // block until it arrives
      }
      case 50: // OVERLAY_CUTOFF
        overlayCutoff = codeAt(s.pc++);
        break;
      case 51: { // DRAW_TEXT
        uint8_t strIdx = codeAt(s.pc++);
        uint8_t x = codeAt(s.pc++);
        uint8_t y = codeAt(s.pc++);
        uint8_t location = codeAt(s.pc++);
        // Same slot reused when text is redrawn at the same spot, so a script
        // that updates a counter every frame cannot exhaust the table.
        for (uint8_t i = 0; i < drawnTextCount; i++) {
          if (drawnText[i].x == x && drawnText[i].y == y && drawnText[i].location == location) {
            drawnText[i].strIdx = strIdx;
            goto drawTextDone;
          }
        }
        if (drawnTextCount < MAX_DRAWN_TEXT) {
          drawnText[drawnTextCount].strIdx = strIdx;
          drawnText[drawnTextCount].x = x;
          drawnText[drawnTextCount].y = y;
          drawnText[drawnTextCount].location = location;
          drawnTextCount++;
        }
        drawTextDone:
        break;
      }
//#ENDIF
      case 21: { // MENU
        menuVar = codeAt(s.pc++);
        menuCount = codeAt(s.pc++);
        menuFlags = codeAt(s.pc++);
        if (menuCount > MAX_MENU_OPTIONS) menuCount = MAX_MENU_OPTIONS;
        for (uint8_t i = 0; i < menuCount; i++) {
          menuLabels[i] = (const char*)pgm_read_ptr(&strings[codeAt(s.pc++)]);
        }
        menuSel = 0;
        menuActive = true;
        return; // block until the player chooses
      }
      default:
        s.active = false; // corrupt bytecode — bail out
    }
  }
}

// Pixels this actor moves this frame. Speed 0 is the half-speed code: one
// pixel every other frame. Called once per actor per frame so the carry
// toggles at the right rate.
int16_t actorStep(ActorState& a) {
  if (a.speed != 0) return a.speed;
  a.subTick ^= 1;
  return a.subTick;
}

int16_t moveToward(int16_t cur, int16_t goal, int16_t speed) {
  if (cur < goal) return cur + min((int16_t)(goal - cur), speed);
  if (cur > goal) return cur - min((int16_t)(cur - goal), speed);
  return cur;
}

void updatePlayer() {
  if (player.moving) {
    int16_t gx = player.tx * TILE_PX, gy = player.ty * TILE_PX;
    player.px = moveToward(player.px, gx, PLAYER_SPEED);
    player.py = moveToward(player.py, gy, PLAYER_SPEED);
    player.anim++;
    if (player.anim % 8 == 0) player.frame ^= 1;
    if (player.px == gx && player.py == gy) player.moving = false;
    return;
  }
  // A button whose script overrides the default action no longer moves the
  // player or interacts.
  uint8_t blocked = overriddenMask();
  int8_t dx = 0, dy = 0;
  if (arduboy.pressed(LEFT_BUTTON) && !(blocked & LEFT_BUTTON)) dx = -1;
  else if (arduboy.pressed(RIGHT_BUTTON) && !(blocked & RIGHT_BUTTON)) dx = 1;
  else if (arduboy.pressed(UP_BUTTON) && !(blocked & UP_BUTTON)) dy = -1;
  else if (arduboy.pressed(DOWN_BUTTON) && !(blocked & DOWN_BUTTON)) dy = 1;

  int8_t cx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t cy = (player.py + TILE_PX / 2) / TILE_PX;

  if (dx || dy) {
    player.fx = dx; player.fy = dy;
    int8_t nx = cx + dx, ny = cy + dy;
    if (nx >= 0 && nx < (int8_t)sceneW && ny >= 0 && ny < (int8_t)sceneH && !tileSolid(nx, ny)) {
      int8_t ai = actorAt(nx, ny, -1);
      if (ai < 0 || !(actors[ai].def.flags & 1)) {
        player.tx = nx; player.ty = ny; player.moving = true;
      }
    }
  }

  if (arduboy.justPressed(A_BUTTON) && !(blocked & A_BUTTON)) {
    int8_t ai = actorAt(cx + player.fx, cy + player.fy, -1);
    if (ai >= 0 && actors[ai].def.interact != NO_SCRIPT) {
      startScript(actors[ai].def.interact, ai);
    }
  }
}

void checkTriggers() {
  if (player.moving || curScene.triggerCount == 0) return;
  int8_t cx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t cy = (player.py + TILE_PX / 2) / TILE_PX;
  int8_t hit = -1;
  TriggerDef t;
  for (uint8_t i = 0; i < curScene.triggerCount; i++) {
    memcpy_P(&t, &curScene.triggers[i], sizeof(TriggerDef));
    if (cx >= t.x && cx < t.x + t.w && cy >= t.y && cy < t.y + t.h) { hit = i; break; }
  }
  if (hit != armedTrigger && armedTrigger >= 0) {
    // Stepping out of an area — or straight from one into another.
    memcpy_P(&t, &curScene.triggers[armedTrigger], sizeof(TriggerDef));
    if (t.leave != NO_SCRIPT) queueScript(t.leave, 0xFF);
  }
  if (hit < 0) { armedTrigger = -1; return; }
  if (hit != armedTrigger) {
    armedTrigger = hit;
    memcpy_P(&t, &curScene.triggers[hit], sizeof(TriggerDef));
    if (t.enter != NO_SCRIPT) queueScript(t.enter, 0xFF);
  }
}

void checkButtonScripts() {
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonScript[i] == 0xFF) continue;
    if (arduboy.justPressed(pgm_read_byte(&buttonBits[i]))) {
      startScript(buttonScript[i], 0xFF);
      return;
    }
  }
}

void updateActors(bool allowMove) {
  int8_t pcx = (player.px + TILE_PX / 2) / TILE_PX;
  int8_t pcy = (player.py + TILE_PX / 2) / TILE_PX;
  for (uint8_t i = 0; i < actorCount; i++) {
    ActorState& a = actors[i];
    if (a.effectFrames > 0 && --a.effectFrames == 0) a.effect = 0;
    if (a.hidden) continue;
    int16_t step = actorStep(a);
    if ((a.def.flags & 2) && a.animSpeed > 0 && a.animTo > a.animFrom) {
      a.anim++;
      if (a.anim >= a.animSpeed) {
        a.anim = 0;
        if (a.frame < a.animTo) a.frame++;
        else if (a.animLoop) a.frame = a.animFrom;
        // A non-looping state simply stops on its last frame.
      }
    }
    // A scripted Move Actor walks even while the script runs, straight to
    // its target (x first, then y), ignoring collisions.
    if (a.scriptMove) {
      int16_t gx = a.tx * TILE_PX, gy = a.ty * TILE_PX;
      if (a.px != gx) a.px = moveToward(a.px, gx, step);
      else if (a.py != gy) a.py = moveToward(a.py, gy, step);
      if (a.px == gx && a.py == gy) { a.scriptMove = false; a.moving = false; }
      continue;
    }
    if (!allowMove || a.def.movement == 0) continue;
    if (a.moving) {
      int16_t gx = a.tx * TILE_PX, gy = a.ty * TILE_PX;
      a.px = moveToward(a.px, gx, step);
      a.py = moveToward(a.py, gy, step);
      if (a.px == gx && a.py == gy) a.moving = false;
      continue;
    }
    a.timer++;
    if (a.timer < ACTOR_MOVE_INTERVAL) continue;
    a.timer = 0;
    int8_t dx = 0, dy = 0;
    if (a.def.movement == 1) { // wander
      uint8_t d = random(4);
      dx = d == 0 ? -1 : d == 1 ? 1 : 0;
      dy = d == 2 ? -1 : d == 3 ? 1 : 0;
    } else if (a.def.movement == 2) {
      dx = a.dir;
    } else if (a.def.movement == 3) {
      dy = a.dir;
    }
    int8_t nx = a.tx + dx, ny = a.ty + dy;
    bool blocked = nx < 0 || nx >= (int8_t)sceneW || ny < 0 || ny >= (int8_t)sceneH ||
      tileSolid(nx, ny) || actorAt(nx, ny, i) >= 0 ||
      (nx == pcx && ny == pcy) || (nx == player.tx && ny == player.ty);
    if (blocked) {
      if (a.def.movement >= 2) a.dir = -a.dir;
      continue;
    }
    a.tx = nx; a.ty = ny; a.moving = true;
  }
}

void updateCamera() {
  int16_t maxX = (int16_t)sceneW * TILE_PX - 128;
  int16_t maxY = (int16_t)sceneH * TILE_PX - 64;
  camX = player.px - (128 / 2 - TILE_PX / 2);
  camY = player.py - (64 / 2 - TILE_PX / 2);
  if (camX < 0) camX = 0;
  if (camX > maxX) camX = maxX;
  if (camY < 0) camY = 0;
  if (camY > maxY) camY = maxY;
  if (maxX <= 0) camX = 0;
  if (maxY <= 0) camY = 0;
}

void drawTextbox() {
//#IF OVERLAY
  if (overlayCutoff <= 38) return; // cut off above the dialogue box
//#ENDIF
  arduboy.fillRect(0, 38, 128, 26, BLACK);
  arduboy.drawRect(0, 38, 128, 26, WHITE);
  walkText(4, 40, textStr, textPageStart, textShown, true);
  uint16_t pageLen = walkText(0, 0, textStr, textPageStart, 0xFFFF, false);
  if (textShown >= pageLen && (arduboy.frameCount >> 4) & 1) {
    arduboy.drawPixel(122, 59, WHITE);
    arduboy.drawPixel(123, 59, WHITE);
    arduboy.drawPixel(124, 59, WHITE);
    arduboy.drawPixel(123, 60, WHITE);
  }
}

//#IF FADE
// Ordered dither over the whole scene. Dialogue and menus are drawn after this
// so a fade never swallows the text the player is reading. Working straight on
// the frame buffer keeps it to one pass over the 1KB of screen RAM.
void applyFade() {
  if (fadeLevel == 0) return;
  uint8_t* buf = arduboy.getBuffer();
  if (fadeLevel >= FADE_LEVELS) { memset(buf, 0, WIDTH * HEIGHT / 8); return; }
  for (uint8_t page = 0; page < HEIGHT / 8; page++) {
    for (uint8_t x = 0; x < WIDTH; x++) {
      uint8_t b = buf[page * WIDTH + x];
      if (!b) continue;
      for (uint8_t bit = 0; bit < 8; bit++) {
        uint8_t y = page * 8 + bit;
        if (pgm_read_byte(&bayer4[(y & 3) * 4 + (x & 3)]) < fadeLevel) b &= ~(1 << bit);
      }
      buf[page * WIDTH + x] = b;
    }
  }
}

//#ENDIF

//#IF UPDATE_SCRIPTS
// On Update scripts run every frame regardless of what the blocking VM is
// doing, and must finish within the frame — the compiler strips anything that
// could pause them.
void runUpdateScripts() {
  uint8_t sceneBefore = sceneIdx;
  for (uint8_t i = 0; i < actorCount; i++) {
    if (actors[i].hidden || actors[i].def.update == NO_SCRIPT) continue;
    scratch.active = true;
    scratch.pc = pgm_read_word(&scriptOffsets[actors[i].def.update]);
    scratch.self = i;
    scratch.wait = 0;
    scratch.waitActor = -1;
    scratch.waitInput = 0;
    scratch.waitFade = false;
    scratch.waitOverlay = false;
    runScript(scratch);
    // A scene change rebuilds the actor table, so these indices are stale.
    if (sceneIdx != sceneBefore) return;
  }
}
//#ENDIF

void drawFrame() {
  arduboy.clear();
  uint8_t tx0 = camX / TILE_PX;
  uint8_t ty0 = camY / TILE_PX;
  uint8_t tx1 = (camX + 127) / TILE_PX;
  uint8_t ty1 = (camY + 63) / TILE_PX;
  if (tx1 >= sceneW) tx1 = sceneW - 1;
  if (ty1 >= sceneH) ty1 = sceneH - 1;
  for (uint8_t ty = ty0; ty <= ty1; ty++) {
    for (uint8_t tx = tx0; tx <= tx1; tx++) {
      Sprites::drawOverwrite(tx * TILE_PX - camX, ty * TILE_PX - camY, tileset, tileAt(tx, ty));
    }
  }
//#IF OVERLAY
  drawTexts(0);
//#ENDIF
  for (uint8_t i = 0; i < actorCount; i++) {
    ActorState& a = actors[i];
    if (a.hidden) continue;
    // Flicker blanks the actor on alternate pairs of frames; shake jitters it
    // one pixel sideways. Both are pure draw-time effects.
    if (a.effect == 1 && ((arduboy.frameCount >> 1) & 1)) continue;
    int8_t shake = (a.effect == 2) ? ((arduboy.frameCount & 1) ? 1 : -1) : 0;
    const uint8_t* spr = (const uint8_t*)pgm_read_ptr(&sprites[a.spriteIdx]);
    Sprites::drawSelfMasked(a.px + shake - camX, a.py - camY, spr, a.frame);
  }
//#IF PROJECTILES
  for (uint8_t i = 0; i < MAX_PROJECTILES; i++) {
    Projectile& p = projectiles[i];
    if (!p.active) continue;
    const uint8_t* spr = (const uint8_t*)pgm_read_ptr(&sprites[p.spriteIdx]);
    Sprites::drawSelfMasked(p.px - camX, p.py - camY, spr, 0);
  }
//#ENDIF
  const uint8_t* pspr = (const uint8_t*)pgm_read_ptr(&sprites[PLAYER_SPRITE]);
  Sprites::drawSelfMasked(player.px - camX, player.py - camY, pspr, player.frame);
//#IF FADE
  applyFade();
//#ENDIF
//#IF OVERLAY
  drawOverlay();
  drawTexts(DRAW_TEXT_OVERLAY);
//#ENDIF
  if (script.active && textStr != nullptr) drawTextbox();
  if (menuActive) drawMenu();
}

void setup() {
  arduboy.begin();
  arduboy.setFrameRate(60);
  arduboy.initRandomSeed();
  for (uint8_t i = 0; i < NUM_VARS; i++) vars[i] = 0;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) buttonScript[i] = 0xFF;
  player.fx = 0; player.fy = 1;
  player.frame = 0; player.anim = 0;
  loadScene(START_SCENE, START_X, START_Y, true);
}

void loop() {
  if (!arduboy.nextFrame()) return;
  arduboy.pollButtons();

  // Restart a looping song when it finishes.
  if (loopSong >= 0 && !sound.playing()) {
    const uint16_t* s = (const uint16_t*)pgm_read_ptr(&songs[(uint8_t)loopSong]);
    sound.tones(s);
  }

//#IF FADE
  stepFade();
//#ENDIF

  // A finished init script hands over to the next one queued by loadScene.
  if (!script.active) startNextQueued();

  if (script.active) {
    runScript(script);
  } else {
    // Default actions run first (with overridden buttons masked out), then any
    // script attached to a button that was just pressed takes over.
    updatePlayer();
    checkTriggers();
//#IF COLLISIONS
    if (!script.active) checkCollisions();
//#ENDIF
    if (!script.active) checkButtonScripts();
  }
  updateActors(!script.active);
//#IF OVERLAY
  updateOverlay();
//#ENDIF
//#IF PROJECTILES
  updateProjectiles();
//#ENDIF
//#IF UPDATE_SCRIPTS
  runUpdateScripts();
//#ENDIF
  updateCamera();

  drawFrame();
  arduboy.display();
}
`;

  return { ino: stripFeatures(out, g.features), compiled: g, warnings: g.warnings };
}
