// GENERATED by tools/measure_flash.mjs — do not edit by hand.
//
// What the engine costs in flash on an ATmega32u4, measured by compiling a bare
// game and then one variant per optional subsystem. Regenerate whenever the
// engine changes; tools/test_runtime.mjs checks these against a real build so
// they cannot drift silently.
//
// Measured 2026-08-17.

// Usable flash on an Arduboy once the bootloader has its share.
export const FLASH_BUDGET = 28672;

// A game with no optional subsystems at all, including the Arduboy2 and
// ArduboyTones libraries it always links.
export const FLASH_BASELINE = 21780;

// Extra bytes each subsystem adds when a game scripts it.
export const FLASH_SUBSYSTEM = {
  PROJECTILES: 1024,
  EXPR: 934,
  OVERLAY: 902,
  COLLISIONS: 422,
  FADE: 316,
  SCENE_STACK: 256,
  TEXT_VARS: 186,
  UPDATE_SCRIPTS: 170,
  SWITCH: 152,
  SONGS: 56,
  MENUS: 16,
  BUTTON_SCRIPTS: 8,
  TEXT: 8,
  LED: 6,
  EFFECTS: 4,
  SAVES: 2,
};
