#!/usr/bin/env node
// Bundles ArduStudio into ONE self-contained HTML file that runs offline with
// no web server: dist/ArduStudio.html.
//
// Why a bundle at all: the app is written as ES modules, and Chromium refuses to
// load module scripts over file:// (they are subject to CORS, and a file:// origin
// is opaque). A single classic <script> has no such restriction, so esbuild
// bundles everything into one IIFE and we inline it.
//
// The Electron app loads this same file, so desktop and browser run identical code.
//
// Usage: node tools/build_offline.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, 'dist');
const outFile = join(outDir, 'ArduStudio.html');

// 1. Bundle the module graph into a single IIFE.
const bundled = await esbuild.build({
  entryPoints: [join(root, 'js', 'main.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  write: false,
  legalComments: 'inline', // keep the Arduboy2 font attribution in font5x7.js
});
const js = bundled.outputFiles[0].text;

// 2. Inline the stylesheet and the bundle into index.html.
let html = readFileSync(join(root, 'index.html'), 'utf8');
const css = readFileSync(join(root, 'css', 'style.css'), 'utf8');

const before = html;
html = html.replace(
  /<link rel="stylesheet" href="css\/style\.css">/,
  () => `<style>\n${css}\n</style>`,
);
if (html === before) throw new Error('Could not find the stylesheet link in index.html');

const beforeJs = html;
html = html.replace(
  /<script type="module" src="js\/main\.js"><\/script>/,
  // A function replacer avoids `$&`-style substitutions being interpreted in the code.
  () => `<script>\n${js}\n</script>`,
);
if (html === beforeJs) throw new Error('Could not find the module script tag in index.html');

// 3. Note in the file itself that it is generated, so nobody hand-edits it.
html = html.replace(
  '<head>',
  '<head>\n<!-- Generated by tools/build_offline.mjs — do not edit; edit the sources and rebuild. -->',
);

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, html);

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`dist/ArduStudio.html written — ${kb(html.length)} (js ${kb(js.length)}, css ${kb(css.length)})`);

// Sanity: the output must not reference any local file any more.
const leftovers = [...html.matchAll(/(?:src|href)="(?!data:|https?:|#)([^"]+)"/g)].map((m) => m[1]);
if (leftovers.length) {
  console.error(`WARNING: still references local files: ${leftovers.join(', ')}`);
  process.exit(1);
}
console.log('Self-contained: no local file references remain.');
